// Generated by can compile from T; do not edit.
export const appDefinition={id:"T",uses:[],packages:{T:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{},pages:[],disabled:[]};
async function $can$s$542e66(c,$can$l$303a61){return $can$l$303a61;}
async function $can$s$542e67(c){return await $can$s$542e66(c);}
export function canApp(){
return {
"T.f":$can$s$542e66,
"T.g":$can$s$542e67,
};}
