// Generated by can compile from T; do not edit.
import { format } from "@canlang/stdlib";
import { message as $can$u$6d657373616765 } from "@canlang/ui";
export const appDefinition={id:"T",uses:[],packages:{T:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{},pages:[],disabled:[]};
async function $can$s$542e67(c,$can$l$303a746172676574){return format(c,$can$u$6d657373616765("Hi",{nl:"Hoi"}),{locale:null});}
export function canApp(){
return {
"T.g":$can$s$542e67,
};}
