// Generated by can compile from AwaitAudit; do not edit.
import { require as check, contains, hasRole } from "@canlang/stdlib";
export const $can$o$417761697441756469742e72756e="AwaitAudit.run";
export const appDefinition={id:"AwaitAudit",uses:[],packages:{AwaitAudit:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{"AwaitAudit.run":{handler:"AwaitAudit.run",inputs:{},by:"members",read:true,result:{type:"bool"}}},policy:{roles:[],models:{},operations:{"AwaitAudit.run":{by:["members"]}}},pages:[],disabled:[]};
export function canApp(){
return {
operations:[{"name":"AwaitAudit.run","kind":"read","description":"","inputs":{"fields":[]}}],
async "AwaitAudit.run"(c,{}){
check(hasRole(c,"members"),"forbidden");
return false && await (($can$a$30)=>contains($can$a$30[1],$can$a$30[0]))(["ABC","BC"]);
},
policy:{roles:[],models:{},operations:{"AwaitAudit.run":{by:["members"]}}},
};}
