import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
const root='/private/tmp/canlang-roadmap-f1-db57c379';
const {loadArtifactDescriptors}=await import(`${root}/packages/state/dist/src/invocation/registry.js`);
const artifact=JSON.parse(await readFile(new URL('./artifacts/bounded-compile.json',import.meta.url)));
const loaded=loadArtifactDescriptors(artifact,{by:'public'});
assert.deepEqual([...loaded.registry.keys()],artifact.operations.map(op=>op.name));
assert.deepEqual(loaded.registry.get('Bounded.Job.create').descriptor.inputs.map(input=>[input.name,input.kind]),[['title','string'],['count','integer'],['enabled','boolean'],['account','ref']]);
assert.deepEqual(loaded.models.map(m=>m.name),['Bounded.Account','Bounded.Job']);
assert.equal(loaded.registry.get('Bounded.advance').descriptor.inputs[0].kind,'ref');
assert.equal(loaded.registry.get('Bounded.advance').descriptor.inputs[0].model,'Bounded.Job');
assert.equal(loaded.registry.get('Bounded.advance').descriptor.inputs[0].versioned,true);
const model=loaded.models.find(m=>m.name==='Bounded.Job');
assert.equal(model.fields.count.default.value,'1');
assert.equal(model.fields.enabled.default.value,true);
assert.equal(model.fields.title.default.value,'test');
assert.equal(model.fields.status.machine.initial,'idle');
assert.deepEqual(model.fields.status.machine.transitions,[{from:'idle',to:'queued',operation:'Bounded.advance'},{from:'queued',to:'ready',operation:'Bounded.advance'}]);
assert.deepEqual([...loaded.nullableFields.get('Bounded.Job')],['account']);
assert.equal(loaded.refs.get('Bounded.Job')[0].model,'Bounded.Account');
const result={status:'passed',artifactUnchanged:true,models:loaded.models,operations:[...loaded.registry.keys()],refs:[...loaded.refs],nullableFields:[...loaded.nullableFields].map(([k,v])=>[k,[...v]])};
await writeFile(new URL('./loader-results.json',import.meta.url),JSON.stringify(result,null,2)+'\n');
console.log('Unchanged actual CLI artifact loaded: identity, reference/version, scalar defaults, flat machine metadata.');
