/**
 * @canlang/state entry: the one authoritative commit engine (internal package).
 * Generated programs import the thin `@canlang/stdlib` facade instead; that
 * assembly re-exports producer surfaces and must never be imported back here.
 */
export { stateCatalog, STATE_ENGINE_VERSION, type StateCatalog } from './catalog.js';
export { StateError, isStateError, ruleFailed } from './errors.js';
export {
  queryRecords,
  queryAggregate,
  type AggregateQueryResult,
  type BaseQueryInput,
  type OwnerRecordsInput,
  type QueryAggregateInput,
  type QueryCallerContext,
  type QueryRecordsInput,
  type ViewerRecordsInput,
} from './query/index.js';
export { STATE_CONTRACT_VERSION } from '@canlang/contracts';
export type {
  StateErrorCode,
  RecordId,
  RecordVersion,
  Revision,
  OperationId,
  OperationName,
  ModelName,
  AdmissionKind,
  Principal,
  TeamScope,
  InvocationContext,
  ReceiptIdentity,
  ReceiptOutcome,
  Receipt,
  ReadAuthority,
  QueryPredicate,
  OrderTerm,
  QuerySpec,
  StoredRow,
  RecordParent,
  DeleteMode,
  DomainWrite,
  HistoryEntry,
  OutboxIntent,
  ScheduleOp,
  CommitBatch,
  CommitResult,
  FenceConflict,
  StoragePort,
  FieldPath,
  AggregateOp,
  AggregateSpec,
  AggregateResult,
  ProjectedRecord,
  AuthorizedRecordsResult,
  AuthorityRowsResult,
} from '@canlang/contracts';
export {
  buildModelTable,
  isParentPathDefault,
  beginOwnerMutation,
  assertOwnerMutationHookContext,
  bindOwnerModelPolicies,
  bindArtifactOwnerModelPolicies,
  checkOwnerModelPolicyDescriptors,
  assertCheckedOwnerModelPolicies,
  runMutationWrites,
  CRUD_MAX_ID_LENGTH,
  crudDefs,
  crudExecute,
  type InterimFieldDef,
  type InterimHook,
  type InterimHookContext,
  type InterimHookOp,
  type InterimInvariant,
  type InterimInvariantView,
  type InterimLock,
  type InterimModelDef,
  type InterimParentPathDefault,
  type InterimRefDef,
  type ModelTable,
  type CheckedOwnerModelPolicies,
  type SourceVerifiedOwnerModelPolicyModule,
  type OwnerModelChange,
  type OwnerModelReadView,
  type OwnerModelPolicyViews,
  type OwnerModelPolicyBinding,
  type OwnerRuleContext,
  type OwnerMutationChange,
  type OwnerMutationHookContext,
  type OwnerMutationInput,
  type OwnerMutationQuery,
  type OwnerMutationReadView,
  type OwnerMutationSession,
  type OwnerMutationStageOptions,
  type OwnerMutationViews,
  type MutationWrite,
  type MutationWritesInput,
  type MutationWritesResult,
  type CrudDefs,
  type CrudDefsOptions,
  type CrudExecuteInput,
  type CrudOperationDef,
  type GeneratedCrudExecuteInput,
  type GeneratedCrudOwnerFrame,
  type GeneratedCrudOwnerFrameFactory,
} from './mutation/index.js';
export { checkJsonSafe, jsonClone } from './internal/json.js';
export {
  STAGING_MAX_ID_LENGTH,
  outboxIntentId,
  stageEffectsStaging,
  stageOutboxIntents,
  stageScheduleOps,
  type StagingContext,
} from './effects/staging.js';
export {
  createInvoker,
  createReadPort,
  createSystemRegistry,
  createTransactionPort,
  defineSystemCommand,
  outboxAckCommand,
  scheduleCancelCommand,
  scheduleReplaceCommand,
  type BoundInvoker,
  type InvokerInput,
  type InvokeArgs,
  type ReadAggregateArgs,
  type ReadOwnerRecordsArgs,
  type ReadPort,
  type ReadPortInput,
  type ReadViewerRecordsArgs,
  type SystemCommandContext,
  type SystemCommandDef,
  type SystemRegistry,
  type SystemRunContext,
  type SystemRunResult,
  type SystemStaging,
  type TransactionPort,
} from './ports/index.js';
export type { MembershipReader } from './policy/roles.js';
export type { PolicyTable } from './policy/grants.js';
export type { OperationRegistry } from './invocation/registry.js';
export type { ClockPort } from './invocation/context.js';
export type { ExecuteHandler } from './invocation/invoke.js';
export {
  activate,
  canonicalUniqueValue,
  checkActivationInventory,
  createMigrationRowBuilder,
  flipToInstalled,
  freezeBeforeRow,
  freshInstallSnapshot,
  publishStagedAndDrops,
  resumeMigration,
  stageNextChunk,
  validateMappedRow,
  validateStaged,
  validateTransition,
  type ActivateInput,
  type ActivationDisposition,
  type FreshInstallInput,
  type FrozenBeforeRow,
  type MigrationMapper,
  type MigrationRowBuilder,
  type OldLockSet,
  type ResumeMigrationInput,
  type ResumeMigrationResult,
  type SeededMigrationRowBuilder,
  type StageNextChunkInput,
  type StageNextChunkResult,
  type ValidatedFieldMapping,
  type ValidatedMigrationPlan,
  type ValidatedModelKind,
  type ValidatedModelMapping,
  type ValidatedOwnerAction,
  type ValidateStagedInput,
} from './migration/index.js';

export { transition, type TransitionContext } from './effects/transition.js';
