// Generated by can compile from T; do not edit.
import { require as check, hasRole } from "@canlang/stdlib";
import { message as $can$u$6d657373616765 } from "@canlang/ui";
export const $can$o$542e73="T.s";
export const appDefinition={id:"T",uses:[],packages:{T:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{"T.s":{handler:"T.s",inputs:{input:{type:"decimal"}},by:"members",read:true,result:{type:"decimal"}}},policy:{roles:[],models:{},operations:{"T.s":{by:["members"]}}},pages:[],disabled:[]};
export function canApp(){
return {
operations:[{"name":"T.s","kind":"read","description":"","inputs":{"fields":[{"name":"input","field":{"kind":"decimal"},"required":true}]}}],
async "T.s"(c,{input:$can$l$303a696e707574}){
check(hasRole(c,"members"),"forbidden");
const $can$l$313a76616c7565 = $can$l$303a696e707574;
const $can$l$323a6d7367 = $can$u$6d657373616765("{x,number}",{},{x:{type:"decimal",value:$can$l$313a76616c7565}});
return $can$l$313a76616c7565;
},
policy:{roles:[],models:{},operations:{"T.s":{by:["members"]}}},
};}
