/**
 * B5-J3 deploy render: a `DeployPlan` serialized two ways — reviewable
 * `wrangler.toml` plus the canonical JSON the diff gate compares.
 *
 * Both renders are deterministic (fixed key order, descriptor order
 * preserved): the same plan always yields the same bytes. TOML strings
 * are minimally escaped; secrets NEVER appear (plans carry names only,
 * and names only where wrangler needs no secret values at all).
 *
 * Schedules render as an OPEN-139 comment ONLY: no cron expression is
 * invented from an interval (see `plan.ts`). When the schedule-backend
 * decision lands, its mapping joins here.
 */
import type { DeployPlan } from "./plan.js";

export interface RenderedPlan {
  toml: string;
  /** Canonical JSON (2-space indent + trailing newline). */
  json: string;
}

function tomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return `"${escaped}"`;
}

/** Render one reviewable `wrangler.toml` from the plan. Fixed section order. */
export function renderWranglerToml(plan: DeployPlan): string {
  const wrangler = plan.wrangler;
  const lines: string[] = [
    "# Generated by can-platform deploy -- review before applying.",
    `name = ${tomlString(wrangler.name)}`,
    `main = ${tomlString(wrangler.main)}`,
    `compatibility_date = ${tomlString(wrangler.compatibility_date)}`,
    "",
  ];
  const varNames = Object.keys(wrangler.vars).sort();
  if (varNames.length > 0) {
    lines.push("[vars]");
    for (const name of varNames) {
      lines.push(`${name} = ${tomlString(wrangler.vars[name] as string)}`);
    }
    lines.push("");
  }
  for (const db of wrangler.d1_databases) {
    lines.push("[[d1_databases]]");
    lines.push(`binding = ${tomlString(db.binding)}`);
    lines.push(`database_name = ${tomlString(db.database_name)}`);
    lines.push(`database_id = ${tomlString(db.database_id)}`);
    lines.push("");
  }
  for (const bucket of wrangler.r2_buckets) {
    lines.push("[[r2_buckets]]");
    lines.push(`binding = ${tomlString(bucket.binding)}`);
    lines.push(`bucket_name = ${tomlString(bucket.bucket_name)}`);
    lines.push("");
  }
  for (const binding of wrangler.durable_objects.bindings) {
    lines.push("[[durable_objects.bindings]]");
    lines.push(`name = ${tomlString(binding.name)}`);
    lines.push(`class_name = ${tomlString(binding.class_name)}`);
    lines.push("");
  }
  for (const producer of wrangler.queues.producers) {
    lines.push("[[queues.producers]]");
    lines.push(`binding = ${tomlString(producer.binding)}`);
    lines.push(`queue = ${tomlString(producer.queue)}`);
    lines.push("");
  }
  for (const service of wrangler.services) {
    lines.push("[[services]]");
    lines.push(`binding = ${tomlString(service.binding)}`);
    lines.push(`service = ${tomlString(service.service)}`);
    lines.push("");
  }
  for (const dataset of wrangler.analytics_engine_datasets) {
    lines.push("[[analytics_engine_datasets]]");
    lines.push(`binding = ${tomlString(dataset.binding)}`);
    lines.push(`dataset = ${tomlString(dataset.dataset)}`);
    lines.push("");
  }
  if (plan.schedules.length > 0) {
    lines.push(
      `# OPEN-139: ${plan.schedules.length} schedule(s) pass through unmapped;`,
      "# no trigger section is emitted until the schedule-backend",
      "# decision lands. Handlers:",
    );
    for (const schedule of plan.schedules) {
      lines.push(`# - ${schedule.handler}`);
    }
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

/** Canonical JSON: the bytes the review gate diffs and stores. */
export function renderPlanJson(plan: DeployPlan): string {
  return `${JSON.stringify(plan, null, 2)}\n`;
}

export function renderDeployPlan(plan: DeployPlan): RenderedPlan {
  return { toml: renderWranglerToml(plan), json: renderPlanJson(plan) };
}
