import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {construct,negative} from './public-module.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../../../..');
const req=createRequire(root+'/package.json');
const resolved=Object.fromEntries(['values','stdlib'].map(n=>[n,req.resolve('@canlang/'+n)]));
const paths=['compiler/src/syntax/lexer.rs','compiler/src/analysis/types.rs','compiler/src/codegen/ir.rs','compiler/src/codegen/js.rs','docs/specification/DESIGN.md','docs/specification/DECISIONS.md',...['values','stdlib'].flatMap(n=>[`packages/${n}/package.json`,`packages/${n}/src/index.ts`,`packages/${n}/dist/src/index.js`]),...['decimal','catalog','wire','schema','internal/wire-core','internal/schema-core'].flatMap(n=>[`packages/values/src/${n}.ts`,`packages/values/dist/src/${n}.js`]),...['backend','carriers'].flatMap(n=>[`packages/values/bindings/${n}.ts`,`packages/values/dist/bindings/${n}.js`]),'packages/values/dist/catalog.json'];
const pins=()=>Object.fromEntries(paths.map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(root+'/'+p)).digest('hex')]));
const before=pins();
const v=await import(pathToFileURL(resolved.values));const std=await import(pathToFileURL(resolved.stdlib));
const cap=fn=>{try{return {ok:true,value:fn()};}catch(e){return {ok:false,name:e.name,code:e.code,message:e.message};}};
const inputs=['1.50','0.00','-0.00','-1.50','99999999999999999999999999999999999999','99999999999999999999.123456789012345678','0.000000000000000001','0001.50','1.0000000000000000000','999999999999999999999999999999999999999','1e2','+1.5'];
const controls=inputs.map(text=>({text,publicModule:cap(()=>{const value=construct(text);return {value,frozen:Object.isFrozen(value),sameOwnerIdentity:construct(text) instanceof v.Decimal,wire:v.encodeValue('decimal',value),decoded:v.decodeValue('decimal',v.encodeValue('decimal',value))};})}));
const schema=v.normalizeSchema({contracts:{C:{fields:{amount:{type:'decimal',default:'1.50'},optional:{type:'decimal?'},nullableDefault:{type:'decimal?',default:'2.00'}}}}});
const schemaControls=[['create-omission',()=>v.validateValue(schema,'C',{},'create')],['create-explicit-null',()=>v.validateValue(schema,'C',{optional:null,nullableDefault:null},'create')],['create-provided',()=>v.validateValue(schema,'C',{amount:'9.00'},'create')],['update-omission',()=>{const result=v.validateValue(schema,'C',{},'update');return {result,amountOmitted:v.isUpdateOmitted(result.amount),optionalOmitted:v.isUpdateOmitted(result.optional),defaultOmitted:v.isUpdateOmitted(result.nullableDefault)};}],['nonnullable-null',()=>v.validateValue(schema,'C',{amount:null},'create')]].map(([id,fn])=>({id,result:cap(fn)}));
const catalog=JSON.parse(fs.readFileSync(root+'/packages/values/dist/catalog.json'));
const carriers=await import('@canlang/values/bindings/carriers');
const bindingCarrier=carriers.tag(construct('1.50'));
const bindingRoundtrip=carriers.reconstruct(bindingCarrier);
if(bindingRoundtrip.coef!==150n || bindingRoundtrip.scale!==2)throw new Error('binding carrier changed coefficient/scale');
if(construct('99999999999999999999999999999999999999').coef!==99999999999999999999999999999999999999n)throw new Error('large magnitude changed');
if(construct('1.50').coef!==150n || construct('1.50').scale!==2)throw new Error('authored scale changed');
const outcome={bindingCarrier,bindingRoundtrip,resolved,profile:{node:process.version},publicExports:{parseDecimalType:typeof v.parseDecimal,stdlibParseDecimalType:typeof std.parseDecimal,sameFunction:v.parseDecimal===std.parseDecimal,valuesDecimalFromInteger:typeof v.decimalFromInteger,stdlibDecimalFromInteger:typeof std.decimalFromInteger},catalogKeys:Object.keys(catalog),constructorCatalogMentions:JSON.stringify(catalog).includes('parseDecimal'),controls,unaryNegative:negative('1.50'),schemaControls,nullableWire:cap(()=>v.decodeValue('decimal?',null)),bindingExports:Object.keys(await import('@canlang/values/bindings/carriers'))};
const after=pins();
const json=x=>JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString()+'n':v,2)+'\n';
fs.writeFileSync(here+'/pins.json',json({before,after,changes:paths.filter(p=>before[p]!==after[p]),resolved,profile:{node:process.version}}));
fs.writeFileSync(here+'/outcomes.json',json(outcome));
console.log(json({publicExports:outcome.publicExports,controls:controls.map(c=>[c.text,c.publicModule]),schemaControls,changedPins:paths.filter(p=>before[p]!==after[p])}));
