import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { runInNewContext } from 'node:vm';
import assert from 'node:assert/strict';
import { renderReferenceMarkdown } from '../../../../../packages/interfaces/dist/src/docs/reference.js';
import { Window } from '../../../../../node_modules/happy-dom/lib/index.js';
import { marked } from '/Users/vince/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/marked/lib/marked.esm.js';
const testURL = new URL('../../../../../compiler/tests/typed_reference_policy_consumers.rs', import.meta.url);
const logURL = new URL('../../../integration-after-bindings/after-bdd-ui/full-suite-ide-corrected.log', import.meta.url);
const test = readFileSync(testURL, 'utf8');
const log = readFileSync(logURL, 'utf8');
const nodeDefaultLiteral = test.match(/assert.equal\(title.default, ('[^\n]*')\);/)[1];
const expectedDefault = runInNewContext(nodeDefaultLiteral);
assert.deepEqual([...expectedDefault].map(c => c.charCodeAt(0)), [34,97,92,110,34]);
const expectedRow = test.match(/nl.contains\(r#"(\| `title`[^\n]*)"#\)/)[1];
const observedRow = log.split('\n').find(line => line.startsWith('| `title` | `text` | no | no |'));
const model = { version:1, sourceRevision:'probe', catalogVersion:null, languageVersion:'1', appDefaultLocale:'en', owners:[{name:'Shop', declarations:[{owner:'Shop',name:'Gadget',kind:'model',fields:[{name:'title',type:'text',nullable:false,creationRequired:false,default:expectedDefault,constraints:[],description:{source:'',sourceLang:'en',variants:[],location:{sourceId:'probe',start:0,end:1}}}],examples:[],location:{sourceId:'probe',start:0,end:1}}],operations:[]}],availability:{status:'unknown'}};
const markdown = renderReferenceMarkdown(model);
const row = markdown.split('\n').find(line => line.startsWith('| `title`'));
assert.equal(row, observedRow);
const window = new Window();window.document.body.innerHTML = marked.parse(markdown,{gfm:true,breaks:false});
const domDefault = window.document.querySelectorAll('tbody td')[4].querySelector('code').textContent;
assert.equal(domDefault, expectedDefault);
const evidence = { testSha256:createHash('sha256').update(test).digest('hex'), failureLogSha256:createHash('sha256').update(log).digest('hex'), nodeDefaultLiteral, expectedDefault, expectedDefaultCodePoints:[...expectedDefault].map(c=>c.charCodeAt(0)), expectedRow, observedRow, publicRenderedRow:row, domDefault, rawRustAssertionMatches:expectedRow===row, scope:'existing GFM DOM code text proof plus actual failed CLI output and runtime typed-model assertion; fresh integration receipt is supplied separately by root' };
writeFileSync(new URL('./raw.json',import.meta.url),JSON.stringify(evidence,null,2)+'\n');
console.log(JSON.stringify(evidence));
assert.equal(expectedRow,row,'Rust raw-string Markdown expectation must use one literal backslash');
