import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const artifact=JSON.parse(readFileSync(process.argv[2],'utf8'));
assert.equal(artifact.modules.length,1);
const module=artifact.modules[0];
const path=resolve(dirname(process.argv[2]),'static-emitted.mjs');
writeFileSync(path,module.js);
const generated=await import(pathToFileURL(path));
const page=generated.appDefinition.pages[0];
const bindings=await page.admit({});
const html=await page.render({appDefaultLocale:'en',preferredLocales:['nl']},bindings);
assert.ok(html.includes('Title &lt;&amp;&gt;'));
assert.ok(!html.includes('UNREACHED'));
for(const sentinel of ['OUTER_SENTINEL','INNER_SENTINEL','SIBLING_SENTINEL']) assert.equal(html.split(sentinel).length-1,1);
assert.ok(html.includes('aria-label="Over"'));
const radios=[...html.matchAll(/<input type="radio"[^>]*>/g)].map(match=>match[0]);
assert.equal(radios.length,3);
assert.ok(radios.every(radio=>radio.includes(' checked')));
assert.ok(radios[0].includes(' value="1"'));
const names=radios.map(radio=>/ name="([^"]+)"/.exec(radio)[1]);
assert.equal(new Set(names).size,3);
const ids=[...html.matchAll(/ id="([^"]+)"/g)].map(match=>match[1]);
assert.equal(new Set(ids).size,ids.length);
console.log(JSON.stringify({status:'passed',scope:'unchanged generated static module to installed public UI; no query',checks:['literal escaped Card title','whole item gate','localized surviving caption','nested and sibling IDs','first surviving ordinal','sentinels once'],radio_groups:names},null,2));
