// Generated by can compile from Audit; do not edit.
import { contains, format } from "@canlang/stdlib";
import { message as $can$u$6d657373616765 } from "@canlang/ui";
export const appDefinition={id:"Audit",uses:[],packages:{Audit:{roles:{}}},bindings:{},contracts:{"Audit.Input":{fields:{template:{type:"text"},value:{type:"text"}}}},events:{},capabilities:{},models:{},preferences:{},operations:{},pages:[],disabled:[]};
async function $can$s$41756469742e6964656e74697479(c,$can$l$303a76){return $can$l$303a76;}
async function $can$s$41756469742e70616972(c,$can$l$313a6669727374,$can$l$323a7365636f6e64,$can$l$333a7468697264){if($can$l$323a7365636f6e64===undefined){$can$l$323a7365636f6e64=$can$l$313a6669727374;}if($can$l$333a7468697264===undefined){$can$l$333a7468697264=$can$l$323a7365636f6e64;}return format("{first}/{second}/{third}",{first:$can$l$313a6669727374,second:$can$l$323a7365636f6e64,third:$can$l$333a7468697264});}
async function $can$s$41756469742e72656f726465726564(c,$can$l$343a76){return await (($can$a$35)=>$can$s$41756469742e70616972(c,$can$a$35[1],void 0,$can$a$35[0]))([$can$l$343a76.value,$can$l$343a76.template]);}
async function $can$s$41756469742e6d69786564(c,$can$l$363a76){return await (($can$a$37)=>$can$s$41756469742e70616972(c,$can$a$37[0],void 0,$can$a$37[1]))([$can$l$363a76.template,$can$l$363a76.value]);}
async function $can$s$41756469742e6275696c74696e(c,$can$l$383a76){return (($can$a$39)=>contains($can$a$39[1],$can$a$39[0]))([$can$l$383a76.value,$can$l$383a76.template]);}
async function $can$s$41756469742e6e6573746564(c,$can$l$31303a76){return await (($can$a$3131)=>$can$s$41756469742e70616972(c,$can$a$3131[1],void 0,$can$a$3131[0]))([await $can$s$41756469742e6964656e74697479(c,$can$l$31303a76.value),await $can$s$41756469742e6964656e74697479(c,$can$l$31303a76.template)]);}
async function $can$s$41756469742e736b6970(c,$can$l$31323a76){return true || (($can$a$3133)=>contains($can$a$3133[1],$can$a$3133[0]))([$can$l$31323a76.value,$can$l$31323a76.template]);}
async function $can$s$41756469742e6e756c6c61626c65(c,$can$l$31343a6669727374,$can$l$31353a7365636f6e64){if($can$l$31343a6669727374===undefined){$can$l$31343a6669727374="fallback";}if($can$l$31353a7365636f6e64===undefined){$can$l$31353a7365636f6e64=$can$l$31343a6669727374;}return $can$l$31353a7365636f6e64;}
async function $can$s$41756469742e6e756c6c5f6e616d6564(c){return await (($can$a$3136)=>$can$s$41756469742e6e756c6c61626c65(c,$can$a$3136[0],void 0))([null]);}
async function $can$s$41756469742e6e756c6c5f686f6c65(c){return await (($can$a$3137)=>$can$s$41756469742e6e756c6c61626c65(c,void 0,$can$a$3137[0]))([null]);}
async function $can$s$41756469742e6e756c6c5f6f6d6974746564(c){return await (($can$a$3138)=>$can$s$41756469742e6e756c6c61626c65(c,void 0,void 0))([]);}
async function $can$s$41756469742e64796e616d6963(c,$can$l$31393a76){return (($can$a$3230)=>format($can$a$3230[1],$can$a$3230[0]))([{name:$can$l$31393a76.value},$can$l$31393a76.template]);}
async function $can$s$41756469742e65736361706564(c){return (($can$a$3231)=>format($can$a$3231[1],$can$a$3231[0]))([{name:"é"},"{{name}} {{{name}}} }}"]);}
async function $can$s$41756469742e64657363726970746f72(c,$can$l$32323a76){return (($can$a$3233)=>{const $can$l$32343a63=$can$a$3233[1];const $can$l$32353a636c617373=$can$l$32343a63;const $can$l$32363a6177616974=$can$a$3233[0];return $can$u$6d657373616765("{c}/{class}/{await}",{},{c:{type:"text",value:$can$l$32343a63},class:{type:"text",value:$can$l$32353a636c617373},await:{type:"text",value:$can$l$32363a6177616974}});})([$can$l$32323a76.value,$can$l$32323a76.template]);}
async function $can$s$41756469742e64657363726970746f725f64656661756c74(c){return (($can$a$3237)=>{const $can$l$32383a63="C";const $can$l$32393a636c617373=$can$l$32383a63;const $can$l$33303a6177616974=$can$l$32393a636c617373;return $can$u$6d657373616765("{c}/{class}/{await}",{},{c:{type:"text",value:$can$l$32383a63},class:{type:"text",value:$can$l$32393a636c617373},await:{type:"text",value:$can$l$33303a6177616974}});})([]);}
export function canApp(){
return {
"Audit.identity":$can$s$41756469742e6964656e74697479,
"Audit.pair":$can$s$41756469742e70616972,
"Audit.reordered":$can$s$41756469742e72656f726465726564,
"Audit.mixed":$can$s$41756469742e6d69786564,
"Audit.builtin":$can$s$41756469742e6275696c74696e,
"Audit.nested":$can$s$41756469742e6e6573746564,
"Audit.skip":$can$s$41756469742e736b6970,
"Audit.nullable":$can$s$41756469742e6e756c6c61626c65,
"Audit.null_named":$can$s$41756469742e6e756c6c5f6e616d6564,
"Audit.null_hole":$can$s$41756469742e6e756c6c5f686f6c65,
"Audit.null_omitted":$can$s$41756469742e6e756c6c5f6f6d6974746564,
"Audit.dynamic":$can$s$41756469742e64796e616d6963,
"Audit.escaped":$can$s$41756469742e65736361706564,
"Audit.descriptor":$can$s$41756469742e64657363726970746f72,
"Audit.descriptor_default":$can$s$41756469742e64657363726970746f725f64656661756c74,
};}
