// Generated by can compile from R; do not edit.
export const appDefinition={id:"R",uses:[],packages:{R:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{"R.M":{readGrants:[],fields:{email:{type:"email",default:"a@b!"}}}},preferences:{},operations:{},pages:[],disabled:["R.M.create","R.M.update","R.M.delete"]};
export function canApp(){
return {
};}
