// Generated by can compile from Guard; do not edit.
import { require as check, hasRole, lower } from "file:///Users/vince/Projects/canlang/packages/stdlib/dist/src/index.js";
export const $can$o$47756172642e6563686f="Guard.echo";
export const appDefinition={id:"Guard",uses:[],packages:{Guard:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{"Guard.echo":{handler:"Guard.echo",inputs:{value:{type:"text"}},by:"members",read:true,result:{type:"text"}}},policy:{roles:[],models:{},operations:{"Guard.echo":{by:["members"]}}},pages:[],disabled:[]};
export function canApp(){
return {
operations:[{"name":"Guard.echo","kind":"read","description":"","inputs":{"fields":[{"name":"value","field":{"kind":"string"},"required":true}]}}],
async "Guard.echo"(c,{value:$can$l$303a76616c7565}){
check(hasRole(c,"members"),"forbidden");
return lower($can$l$303a76616c7565);
},
policy:{roles:[],models:{},operations:{"Guard.echo":{by:["members"]}}},
};}
//# sourceMappingURL=$can$m$4775617264.mjs.map
