/**
 * Single authored definition of every presentation component owned by lane 05.
 * Entries name the Can word (or infrastructure construct), the @canlang/ui
 * factory, its contract props shape and its availability; implementation
 * slices flip `planned` to `implemented` as factories land. Envelope mirrors
 * the L1/L2 catalog shape; unification with the shared envelope is a later
 * L1/L7 join.
 *
 * C2a: covers all 68 approved Can words from design/UI-COMPONENTS.md plus the
 * non-word infrastructure entries (page-shell, navigation, core constructs,
 * settings/history/copy/board/review/csv-import/file). Every entry carries a
 * binding profile, a header-expression payload, the closed structural
 * attributes named by the design, and (for slotted groups only) the finite
 * slot schema. Appearance tokens arrive in C2b, not here.
 *
 * Signatures on planned words are forward declarations for slices C3-C8:
 * the named `XxxProps` types do NOT exist yet in presentation.ts and land
 * with their implementing slice. Availability is truthful: only factories
 * actually exported from index.ts are marked implemented; CSS reuse inside
 * other renderers (badge, form controls, toolbar join) and shell-internal
 * drawer/dropdown/menu/modal/navbar do not count as selectable components.
 */
import type {
  ComponentCatalog,
  ComponentCatalogEntry,
} from "../../contracts/src/presentation.js";

export const LANE05_CATALOG_VERSION = "0.1.0-lane05-draft";

const ENTRIES: ReadonlyArray<ComponentCatalogEntry> = [
  { id: "page-shell", js: "renderPage", owner: "lane-05", kind: "component", signature: "renderPage(context, descriptor, children, shell?): RenderPageFn", availability: "implemented", profile: "shell", header: "none", notes: "S2: drawer shell, account menu, settings frame, partials." },
  { id: "navigation", js: "buildNavigation", owner: "lane-05", kind: "component", signature: "buildNavigation(candidates, outcomes, options): NavigationResult", availability: "implemented", profile: "shell", header: "none", notes: "S2: discovery shaping; candidates via selectDiscoveryCandidates." },
  { id: "card", js: "card", owner: "lane-05", kind: "component", signature: "card(props: CardProps)", availability: "implemented", profile: "group", header: "text", notes: "S3." },
  { id: "title", js: "title", owner: "lane-05", kind: "component", signature: "title(props: TitleProps)", availability: "implemented", profile: "leaf", header: "text", notes: "S3." },
  { id: "text", js: "text", owner: "lane-05", kind: "component", signature: "text(props: TextProps)", availability: "implemented", profile: "leaf", header: "value", notes: "S3." },
  { id: "content", js: "content", owner: "lane-05", kind: "component", signature: "content(props: ContentProps)", availability: "implemented", profile: "leaf", header: "text", notes: "S3." },
  { id: "list", js: "list", owner: "lane-05", kind: "component", signature: "list(props: ListProps)", availability: "implemented", profile: "collection", header: "query", attributes: ["columns", "order", "search", "filter", "empty", "defaults", "display"], notes: "S3 renderers; S5 search/filter/order/pagination/export/print controls via props.controls." },
  { id: "table", js: "table", owner: "lane-05", kind: "component", signature: "table(props: TableProps)", availability: "implemented", profile: "collection", header: "query", attributes: ["columns", "order", "search", "filter", "empty", "defaults", "display"], notes: "S3 renderers; S5 controls via props.controls." },
  { id: "state", js: "renderState", owner: "lane-05", kind: "component", signature: "renderState(props: SharedStateProps)", availability: "implemented", profile: "leaf", header: "value", notes: "S3: loading/empty/error; S5 adds no-match; validation/conflict/pending arrive with forms." },
  { id: "board", js: "board", owner: "lane-05", kind: "component", signature: "board(props: BoardProps)", availability: "planned", profile: "collection", header: "query", attributes: ["by", "columns", "order", "search", "filter", "empty", "defaults"], notes: "S7: enum-grouped cards, no drag/drop." },
  { id: "calendar", js: "calendar", owner: "lane-05", kind: "component", signature: "calendar(props: CalendarProps)", availability: "planned", profile: "collection", header: "query", attributes: ["start", "end", "columns", "order", "search", "filter", "empty", "defaults"], notes: "C4/C7: one entry; written-shape dispatch — a selector with no endpoints is the C4 field control, a query with start=/end= is the C7 agenda collection; no drag/resize." },
  { id: "stat", js: "stat", owner: "lane-05", kind: "component", signature: "stat(props: StatProps)", availability: "planned", profile: "slotted-group", header: "value", slots: [{ name: "value", required: true, repeatable: false }, { name: "title", required: false, repeatable: false }, { name: "description", required: false, repeatable: false }, { name: "icon", required: false, repeatable: false }], notes: "C5: typed metric leaf (observations) or required value-slot suite; metrics shares this contract." },
  { id: "copy", js: "copy", owner: "lane-05", kind: "component", signature: "copy(props: CopyProps)", availability: "planned", profile: "leaf", header: "value", notes: "S7: clipboard button." },
  { id: "collapse", js: "collapse", owner: "lane-05", kind: "component", signature: "collapse(props: CollapseProps)", availability: "planned", profile: "group", header: "text", attributes: ["display", "open"], notes: "C5: disclosure group; details remains the documented compatibility spelling, including the drawer display exception." },
  { id: "history", js: "history", owner: "lane-05", kind: "component", signature: "history(props: HistoryProps)", availability: "planned", profile: "group", header: "none", notes: "S6: authorized audit Collapse." },
  { id: "tabs", js: "tabs", owner: "lane-05", kind: "component", signature: "tabs(props: TabsProps)", availability: "planned", profile: "group", header: "selector", notes: "C8: bound/unbound view panels; optional preference selector leaf or nonempty tab-child suite." },
  { id: "form", js: "form", owner: "lane-05", kind: "component", signature: "form(props: FormProps)", availability: "implemented", profile: "group", header: "binding", attributes: ["arguments", "fields", "submit", "display", "import", "review"], notes: "S4: typed bound forms; HTMX swap behavior arrives in S5." },
  { id: "edit", js: "edit", owner: "lane-05", kind: "component", signature: "edit(props: EditProps)", availability: "implemented", profile: "group", header: "binding", attributes: ["fields"], notes: "S4: canonical update control." },
  { id: "delete", js: "deleteRecord", owner: "lane-05", kind: "component", signature: "deleteRecord(props: DeleteProps)", availability: "implemented", profile: "leaf", header: "binding", notes: "S4: archive/remove mode; `delete` is reserved, hence the js name." },
  { id: "action", js: "action", owner: "lane-05", kind: "component", signature: "action(props: ActionProps)", availability: "implemented", profile: "leaf", header: "binding", notes: "S4: single bound operation." },
  { id: "actions", js: "actions", owner: "lane-05", kind: "component", signature: "actions(props: ActionsProps)", availability: "implemented", profile: "group", header: "none", notes: "S4: grouped bound operations." },
  { id: "settings", js: "renderSettingsPanel", owner: "lane-05", kind: "component", signature: "renderSettingsPanel(props: SettingsPanelProps)", availability: "planned", profile: "shared-control", header: "none", notes: "S6: base + preference panels for the S2 frame." },
  { id: "export", js: "collectionExportLink", owner: "lane-05", kind: "component", signature: "collectionExportLink(controls: CollectionControls)", availability: "implemented", profile: "leaf", header: "none", notes: "S5: shared CSV-export toolbar link; `export` is reserved, hence the js name." },
  { id: "print", js: "collectionPrintLink", owner: "lane-05", kind: "component", signature: "collectionPrintLink(controls: CollectionControls)", availability: "implemented", profile: "leaf", header: "none", notes: "S5: shared Print toolbar link." },
  { id: "file", js: "fileControl", owner: "lane-05", kind: "component", signature: "fileControl(props: FileProps)", availability: "planned", profile: "field-control", header: "selector", notes: "S7: authorized file/media links and inputs." },
  { id: "review", js: "review", owner: "lane-05", kind: "component", signature: "review(props: ReviewProps)", availability: "planned", profile: "leaf", header: "none", notes: "S7: source-derived company-policy review presentation." },
  { id: "csv-import", js: "csvImport", owner: "lane-05", kind: "component", signature: "csvImport(props: CsvImportProps)", availability: "planned", profile: "group", header: "none", notes: "S7: import=csv panel with optional review." },
  { id: "accordion", js: "accordion", owner: "lane-05", kind: "component", signature: "accordion(props: AccordionProps)", availability: "planned", profile: "group", header: "none", notes: "C5: disclosure group with one open child; suite of collapse children only." },
  { id: "alert", js: "alert", owner: "lane-05", kind: "component", signature: "alert(props: AlertProps)", availability: "planned", profile: "group", header: "value", notes: "C5: readable notice or operation feedback; expression-only leaf or nonempty readable-content suite." },
  { id: "aura", js: "aura", owner: "lane-05", kind: "component", signature: "aura(props: AuraProps)", availability: "planned", profile: "group", header: "none", notes: "C5: decoration around existing content." },
  { id: "avatar", js: "avatar", owner: "lane-05", kind: "component", signature: "avatar(props: AvatarProps)", availability: "planned", profile: "leaf", header: "image", attributes: ["caption", "fallback"], notes: "C3: authorized image or explicit safe fallback; caption/fallback are safe text." },
  { id: "badge", js: "badge", owner: "lane-05", kind: "component", signature: "badge(props: BadgeProps)", availability: "planned", profile: "leaf", header: "value", notes: "C3: readable typed value and owning caption; badge CSS in forms/tables is not a selectable component." },
  { id: "breadcrumbs", js: "breadcrumbs", owner: "lane-05", kind: "component", signature: "breadcrumbs(props: BreadcrumbsProps)", availability: "planned", profile: "shared-control", header: "none", notes: "C3/C6: current declared route ancestry; no authored alternative ancestry." },
  { id: "button", js: "button", owner: "lane-05", kind: "component", signature: "button(props: ButtonProps)", availability: "planned", profile: "bound-control", header: "binding", attributes: ["action", "submit", "target", "opens", "arguments", "caption"], notes: "C6: exactly one binding (action/submit/target/opens); lowers to the existing binding node." },
  { id: "carousel", js: "carousel", owner: "lane-05", kind: "component", signature: "carousel(props: CarouselProps)", availability: "planned", profile: "collection", header: "sequence", slots: [{ name: "item", required: true, repeatable: true }], notes: "C5: ordered readable content; exactly one item template with a sequence operand, else authored items." },
  { id: "chat_bubble", js: "chatBubble", owner: "lane-05", kind: "component", signature: "chatBubble(props: ChatBubbleProps)", availability: "planned", profile: "slotted-group", header: "none", slots: [{ name: "content", required: true, repeatable: false }, { name: "avatar", required: false, repeatable: false }, { name: "header", required: false, repeatable: false }, { name: "footer", required: false, repeatable: false }], notes: "C5: explicit message, author and time; no messaging behavior inferred." },
  { id: "checkbox", js: "checkbox", owner: "lane-05", kind: "component", signature: "checkbox(props: CheckboxProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing boolean input." },
  { id: "countdown", js: "countdown", owner: "lane-05", kind: "component", signature: "countdown(props: CountdownProps)", availability: "planned", profile: "leaf", header: "numeric", notes: "C3: readable numeric/time presentation; view-only, no schedule or transition." },
  { id: "diff", js: "diff", owner: "lane-05", kind: "component", signature: "diff(props: DiffProps)", availability: "planned", profile: "slotted-group", header: "none", slots: [{ name: "before", required: true, repeatable: false }, { name: "after", required: true, repeatable: false }], notes: "C5: two authorized presentation slots; no automatic business comparison." },
  { id: "divider", js: "divider", owner: "lane-05", kind: "component", signature: "divider(props: DividerProps)", availability: "planned", profile: "leaf", header: "text", notes: "C3: separation with an optional authored caption." },
  { id: "dock", js: "dock", owner: "lane-05", kind: "component", signature: "dock(props: DockProps)", availability: "planned", profile: "shared-control", header: "none", attributes: ["pages"], notes: "C6: presentation of canonical authorized destinations." },
  { id: "drawer", js: "drawer", owner: "lane-05", kind: "component", signature: "drawer(props: DrawerProps)", availability: "planned", profile: "slotted-group", header: "text", attributes: ["id"], slots: [{ name: "content", required: true, repeatable: false }, { name: "trigger", required: false, repeatable: false }, { name: "actions", required: false, repeatable: false }], notes: "C5: explicitly activated scoped content; shell-internal drawer does not count as selectable." },
  { id: "dropdown", js: "dropdown", owner: "lane-05", kind: "component", signature: "dropdown(props: DropdownProps)", availability: "planned", profile: "slotted-group", header: "none", slots: [{ name: "trigger", required: true, repeatable: false }, { name: "content", required: true, repeatable: false }], notes: "C5: explicit trigger/content slots with shared focus behavior; shell-internal use does not count." },
  { id: "fab", js: "fab", owner: "lane-05", kind: "component", signature: "fab(props: FabProps)", availability: "planned", profile: "group", header: "none", notes: "C5: presentation of existing canonical actions; no batch transaction." },
  { id: "fieldset", js: "fieldset", owner: "lane-05", kind: "component", signature: "fieldset(props: FieldsetProps)", availability: "planned", profile: "group", header: "text", notes: "C5: group existing form fields without duplicating schemas." },
  { id: "file_input", js: "fileInput", owner: "lane-05", kind: "component", signature: "fileInput(props: FileInputProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing writable file input with the authorized upload/finalization path." },
  { id: "filter", js: "filter", owner: "lane-05", kind: "component", signature: "filter(props: FilterProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing typed view/query selection; in a field owner selects the finite-choice input." },
  { id: "footer", js: "footer", owner: "lane-05", kind: "component", signature: "footer(props: FooterProps)", availability: "planned", profile: "slotted-group", header: "text", slots: [{ name: "content", required: true, repeatable: false }, { name: "start", required: false, repeatable: false }, { name: "end", required: false, repeatable: false }], notes: "C5: page content group; closed content/start/end slot schema or compact grouping." },
  { id: "hero", js: "hero", owner: "lane-05", kind: "component", signature: "hero(props: HeroProps)", availability: "planned", profile: "slotted-group", header: "text", slots: [{ name: "content", required: true, repeatable: false }, { name: "start", required: false, repeatable: false }, { name: "end", required: false, repeatable: false }], notes: "C5: prominent scoped content group; closed content/start/end slot schema or compact grouping." },
  { id: "hover_3d", js: "hover3d", owner: "lane-05", kind: "component", signature: "hover3d(props: Hover3dProps)", availability: "planned", profile: "group", header: "none", notes: "C5: decorative wrapper; interactive descendants invalid." },
  { id: "hover_gallery", js: "hoverGallery", owner: "lane-05", kind: "component", signature: "hoverGallery(props: HoverGalleryProps)", availability: "planned", profile: "collection", header: "sequence", slots: [{ name: "item", required: true, repeatable: true }], notes: "C5: authorized images with touch/keyboard alternatives; at most ten images." },
  { id: "indicator", js: "indicator", owner: "lane-05", kind: "component", signature: "indicator(props: IndicatorProps)", availability: "planned", profile: "slotted-group", header: "none", slots: [{ name: "content", required: true, repeatable: false }, { name: "indicator", required: true, repeatable: false }], notes: "C5: explicit indicator/content slots." },
  { id: "input", js: "input", owner: "lane-05", kind: "component", signature: "input(props: InputProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing writable text or appropriate scalar input." },
  { id: "join", js: "join", owner: "lane-05", kind: "component", signature: "join(props: JoinProps)", availability: "planned", profile: "group", header: "none", notes: "C5: visual grouping of existing controls; toolbar-internal join does not count as selectable." },
  { id: "kbd", js: "kbd", owner: "lane-05", kind: "component", signature: "kbd(props: KbdProps)", availability: "planned", profile: "leaf", header: "text", notes: "C3: shortcut notation; registers no keyboard handler." },
  { id: "label", js: "label", owner: "lane-05", kind: "component", signature: "label(props: LabelProps)", availability: "planned", profile: "field-control", header: "selector", attributes: ["caption"], notes: "C4: moves the owning field's generated label; at most one explicit label per field." },
  { id: "link", js: "link", owner: "lane-05", kind: "component", signature: "link(props: LinkProps)", availability: "planned", profile: "leaf", header: "none", attributes: ["target", "caption"], notes: "C3: checked destination or authorized file URL; no invented route or access." },
  { id: "loading", js: "renderState", owner: "lane-05", kind: "component", signature: "renderState(props: SharedStateProps)", availability: "implemented", profile: "leaf", header: "value", notes: "S3 via renderState; C3 selectable spelling for actual loading feedback or an authored placeholder." },
  { id: "mask", js: "mask", owner: "lane-05", kind: "component", signature: "mask(props: MaskProps)", availability: "planned", profile: "group", header: "none", notes: "C5: visual shape around existing content." },
  { id: "megamenu", js: "megamenu", owner: "lane-05", kind: "component", signature: "megamenu(props: MegamenuProps)", availability: "planned", profile: "shared-control", header: "none", attributes: ["pages"], notes: "C6: authorized page descriptors with shared responsive behavior." },
  { id: "menu", js: "menu", owner: "lane-05", kind: "component", signature: "menu(props: MenuProps)", availability: "planned", profile: "shared-control", header: "none", attributes: ["pages"], notes: "C6: declared destinations or canonical action controls; shell-internal use does not count." },
  { id: "mockup_browser", js: "mockupBrowser", owner: "lane-05", kind: "component", signature: "mockupBrowser(props: MockupBrowserProps)", availability: "planned", profile: "group", header: "none", notes: "C3: presentation wrapper; no browsing engine." },
  { id: "mockup_code", js: "mockupCode", owner: "lane-05", kind: "component", signature: "mockupCode(props: MockupCodeProps)", availability: "planned", profile: "leaf", header: "text", notes: "C3: escaped text; no code execution." },
  { id: "mockup_phone", js: "mockupPhone", owner: "lane-05", kind: "component", signature: "mockupPhone(props: MockupPhoneProps)", availability: "planned", profile: "group", header: "none", notes: "C3: presentation wrapper." },
  { id: "mockup_window", js: "mockupWindow", owner: "lane-05", kind: "component", signature: "mockupWindow(props: MockupWindowProps)", availability: "planned", profile: "group", header: "none", notes: "C3: presentation wrapper." },
  { id: "modal", js: "modal", owner: "lane-05", kind: "component", signature: "modal(props: ModalProps)", availability: "planned", profile: "slotted-group", header: "text", attributes: ["id"], slots: [{ name: "content", required: true, repeatable: false }, { name: "trigger", required: false, repeatable: false }, { name: "actions", required: false, repeatable: false }], notes: "C5: activated scoped content with shared dialog behavior; shell-internal use does not count." },
  { id: "navbar", js: "navbar", owner: "lane-05", kind: "component", signature: "navbar(props: NavbarProps)", availability: "planned", profile: "slotted-group", header: "none", attributes: ["pages"], slots: [{ name: "content", required: true, repeatable: false }, { name: "start", required: false, repeatable: false }, { name: "end", required: false, repeatable: false }], notes: "C6: shared navigation presentation with content/start/end slots; shell-internal use does not count." },
  { id: "otp", js: "otp", owner: "lane-05", kind: "component", signature: "otp(props: OtpProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing constrained text input; preserves leading zeros." },
  { id: "pagination", js: "pagination", owner: "lane-05", kind: "component", signature: "pagination(props: PaginationProps)", availability: "planned", profile: "shared-control", header: "none", notes: "C6: consumes the enclosing collection cursor/filter/order state; error elsewhere." },
  { id: "progress", js: "progress", owner: "lane-05", kind: "component", signature: "progress(props: ProgressProps)", availability: "planned", profile: "leaf", header: "numeric", attributes: ["max"], notes: "C3: readable numeric progress with checked bounds; max= required." },
  { id: "radial_progress", js: "radialProgress", owner: "lane-05", kind: "component", signature: "radialProgress(props: RadialProgressProps)", availability: "planned", profile: "leaf", header: "numeric", attributes: ["max"], notes: "C3: same progress data in a circular presentation; max= required." },
  { id: "radio", js: "radio", owner: "lane-05", kind: "component", signature: "radio(props: RadioProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing finite-choice input." },
  { id: "range", js: "range", owner: "lane-05", kind: "component", signature: "range(props: RangeProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing numeric input with suitable owning bounds." },
  { id: "rating", js: "rating", owner: "lane-05", kind: "component", signature: "rating(props: RatingProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing bounded numeric or finite-choice input." },
  { id: "select", js: "select", owner: "lane-05", kind: "component", signature: "select(props: SelectProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing enum/reference selection with current read grants." },
  { id: "skeleton", js: "renderState", owner: "lane-05", kind: "component", signature: "renderState(props: SharedStateProps)", availability: "implemented", profile: "leaf", header: "value", notes: "S3 via renderState; C3 selectable spelling for a loading state or an authored placeholder." },
  { id: "stack", js: "stack", owner: "lane-05", kind: "component", signature: "stack(props: StackProps)", availability: "planned", profile: "group", header: "none", notes: "C5: visual stacking of scoped content." },
  { id: "status", js: "status", owner: "lane-05", kind: "component", signature: "status(props: StatusProps)", availability: "planned", profile: "leaf", header: "value", notes: "C3: explicit readable state with a text alternative." },
  { id: "steps", js: "steps", owner: "lane-05", kind: "component", signature: "steps(props: StepsProps)", availability: "planned", profile: "collection", header: "sequence", slots: [{ name: "item", required: true, repeatable: true }], notes: "C5: readable process stages; defines and executes no workflow." },
  { id: "swap", js: "swap", owner: "lane-05", kind: "component", signature: "swap(props: SwapProps)", availability: "planned", profile: "slotted-group", header: "bool", slots: [{ name: "off", required: true, repeatable: false }, { name: "on", required: true, repeatable: false }], notes: "C5: two presentation slots selected by explicit view state." },
  { id: "text_rotate", js: "textRotate", owner: "lane-05", kind: "component", signature: "textRotate(props: TextRotateProps)", availability: "planned", profile: "collection", header: "sequence", slots: [{ name: "item", required: true, repeatable: true }], notes: "C3: readable text sequence with reduced-motion behavior; at most six items." },
  { id: "textarea", js: "textarea", owner: "lane-05", kind: "component", signature: "textarea(props: TextareaProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing writable text input." },
  { id: "theme_controller", js: "themeController", owner: "lane-05", kind: "component", signature: "themeController(props: ThemeControllerProps)", availability: "planned", profile: "shared-control", header: "none", notes: "C6: existing shared Appearance path with finite theme choices and persistence." },
  { id: "timeline", js: "timeline", owner: "lane-05", kind: "component", signature: "timeline(props: TimelineProps)", availability: "planned", profile: "collection", header: "sequence", slots: [{ name: "item", required: true, repeatable: true }], notes: "C5: ordered authorized events or explicit readable entries." },
  { id: "toast", js: "toast", owner: "lane-05", kind: "component", signature: "toast(props: ToastProps)", availability: "planned", profile: "group", header: "value", notes: "C5: notice placement with shared announcement/dismissal; leaf or readable-content suite." },
  { id: "toggle", js: "toggle", owner: "lane-05", kind: "component", signature: "toggle(props: ToggleProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: existing boolean input, including permitted view settings." },
  { id: "tooltip", js: "tooltip", owner: "lane-05", kind: "component", signature: "tooltip(props: TooltipProps)", availability: "planned", profile: "group", header: "text", notes: "C5: annotation of existing content/control with accessible alternatives." },
  { id: "validator", js: "validator", owner: "lane-05", kind: "component", signature: "validator(props: ValidatorProps)", availability: "planned", profile: "field-control", header: "selector", notes: "C4: places the owning validation outlet; no new constraints or predicates." },
];

export const UI_CATALOG: ComponentCatalog = {
  catalog_version: LANE05_CATALOG_VERSION,
  language_version: null,
  entries: ENTRIES,
};
