/**
 * @canlang/ui public surface for generated code.
 *
 * Generated app JS calls these canonical factories with props/children; the
 * library owns markup/classes and behavior. S1 ships escaping and messages;
 * S2 adds navigation discovery and the page shell; components, forms,
 * collections, htmx, settings and review land in later slices on this surface.
 */

export {
  csvFormulaProtect,
  escapeAttr,
  escapeHtml,
  isSafeUrl,
  isolate,
  safeHref,
} from "./escape.js";
export {
  canonicalDefaultTag,
  canonicalPreferredTags,
  formatDecimalExact,
  formatIntExact,
  formatMessage,
  formatMoneyExact,
  formatScalar,
  isEnumTypeId,
  localeNumberSystem,
  localeSeparators,
  message,
  normalizeTag,
  resolveCaption,
  resolveMessage,
  selectPluralCategory,
} from "./messages.js";
export type {
  Bcp47Tag,
  CaptionContext,
  LocaleNumberSystem,
  MessageParams,
  ResolvedMessage,
  ScalarFormatOptions,
  ThemeTokens,
} from "./messages.js";
export {
  breadcrumbs,
  buildNavigation,
  button,
  dock,
  megamenu,
  menu,
  navbar,
  pagination,
  selectDiscoveryCandidates,
  themeController,
} from "./navigation.js";
export type { BuildNavigationOptions } from "./navigation.js";
export {
  pageDirection,
  pageLocale,
  renderLogin,
  renderPage,
} from "./shell.js";
export {
  card,
  content,
  renderState,
  renderTextValue,
  rowHeading,
  text,
  title,
} from "./components.js";
export {
  collectionExportLink,
  collectionPagination,
  collectionPrintLink,
  collectionShareControls,
  collectionToolbar,
  controlHref,
  list,
  table,
} from "./collections.js";
export {
  assertRegionId,
  fragmentRegion,
  hxAttrs,
  pollTrigger,
  refreshTrigger,
  staleMarker,
  validationStatusSwaps,
} from "./htmx.js";
export { appearanceClasses } from "./appearance.js";
export type { AppearanceOpts } from "./appearance.js";
export {
  badge,
  countdown,
  divider,
  kbd,
  link,
  mockupCode,
  status,
} from "./leaves.js";
export {
  avatar,
  progress,
  radialProgress,
  textRotate,
} from "./media.js";
export {
  calendar,
  checkbox,
  fileInput,
  filter,
  input,
  label,
  otp,
  radio,
  range,
  rating,
  select,
  textarea,
  toggle,
  validator,
} from "./controls.js";
export {
  accordion,
  carousel,
  collapse,
  diff,
  fieldset,
  footer,
  hero,
  join,
  stack,
  stat,
  steps,
  timeline,
} from "./groups.js";
export {
  alert,
  aura,
  chatBubble,
  drawer,
  dropdown,
  fab,
  hover3d,
  hoverGallery,
  indicator,
  mask,
  modal,
  swap,
  toast,
  tooltip,
} from "./overlays.js";
export type { ControlQueryState } from "./collections.js";
export {
  action,
  actions,
  assertFieldPath,
  deleteRecord,
  edit,
  fieldErrorOutletId,
  fieldInputId,
  fieldInputName,
  form,
  formatDatetimeLocal,
  pointerToFieldName,
} from "./forms.js";
export { LANE05_CATALOG_VERSION, UI_CATALOG } from "./catalog.js";
// Temporary B0 wiring: re-exported contract types until lane 7 assembles
// @canlang/contracts; see README.
export type {
  AccordionItem,
  AccordionProps,
  AccountMenuData,
  ActionProps,
  ActionsProps,
  AdmittedBindings,
  AdmitFn,
  AdmissionOutcome,
  AlertProps,
  AppearanceOrientation,
  AppearanceSize,
  AppearanceTone,
  AppearanceVariant,
  AuraProps,
  AvatarProps,
  BadgeProps,
  BoundArguments,
  Bcp47Tag as ContractBcp47Tag,
  BreadcrumbsProps,
  ButtonActionBinding,
  ButtonProps,
  CalendarAgendaProps,
  CalendarFieldProps,
  CalendarProps,
  CardProps,
  CarouselProps,
  ChatBubbleProps,
  CheckboxProps,
  CollapseProps,
  CollectionControls,
  CollectionPagination,
  CollectionSearch,
  ColumnMeta,
  ComponentAppearance,
  ComponentCatalog,
  ComponentCatalogEntry,
  ComponentHeaderExpr,
  ComponentProfile,
  ComponentSlotDef,
  ContentProps,
  CountdownProps,
  DeleteProps,
  DeliveryReceiptView,
  DiffProps,
  DividerProps,
  DockProps,
  DrawerProps,
  DropdownProps,
  EditProps,
  FabProps,
  FieldControlKind,
  FieldControlProps,
  FieldsetProps,
  FileInputProps,
  FilterCondition,
  FilterOperator,
  FilterProps,
  FooterProps,
  FooterSlots,
  FormFieldDef,
  FormFieldOption,
  FormMode,
  FormOutcome,
  FormProps,
  FragmentRegionProps,
  HeroProps,
  HeroSlots,
  Hover3dProps,
  HoverGalleryImage,
  HoverGalleryProps,
  HtmxRequest,
  IndicatorProps,
  InputProps,
  JoinProps,
  KbdProps,
  LabelProps,
  LinkProps,
  ListProps,
  ListQueryArgs,
  ListQueryResult,
  LoginProps,
  MaskProps,
  MegamenuProps,
  MenuProps,
  MessageDescriptor,
  MessageFactory,
  MessageParamValue,
  MessageValue,
  MessageVariantMap,
  MockupCodeProps,
  ModalProps,
  NavbarProps,
  NavigationEntry,
  NavigationGroup,
  NavigationResult,
  OperationRef,
  OrderSelector,
  OtpProps,
  OwnerLabels,
  PageChild,
  PageChildren,
  PageDescriptor,
  PaginationProps,
  PollProps,
  PresentationContext,
  ProgressProps,
  RadialProgressProps,
  RadioProps,
  RangeProps,
  RatingProps,
  RecordIdentity,
  RenderFn,
  RenderPageFn,
  RowQueryRunner,
  RowView,
  SelectProps,
  SettingsFrameData,
  SettingsSection,
  SharedStateProps,
  ShellData,
  ShellRoutes,
  StackProps,
  StaleMarkerProps,
  StatProps,
  StatusProps,
  StatusSwap,
  StepItem,
  StepsProps,
  SwapProps,
  SwapStrategy,
  TableProps,
  TeamOption,
  TextareaProps,
  TextProps,
  TextRotateProps,
  TextValue,
  TimelineItem,
  TimelineProps,
  ToastProps,
  ToggleProps,
  TooltipProps,
  ValidatorProps,
  ThemeAccent,
  ThemeControllerProps,
  ThemeDensity,
  ThemeMode,
  ThemeOption,
  ThemeTokens as ContractThemeTokens,
  TitleProps,
} from "../../contracts/src/presentation.js";
export {
  CSRF_FIELD,
  DEFAULT_THEME,
  PRESENTATION_CONTRACT_VERSION,
  TEAM_FIELD,
} from "../../contracts/src/presentation.js";
