// Generated by can compile from Win; do not edit.
import { contains } from "@canlang/stdlib";
export const appDefinition={id:"Win",uses:[],packages:{Win:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{},pages:[],disabled:[]};
async function $can$s$57696e2e72756e(c){return (($can$a$30)=>contains($can$a$30[1],$can$a$30[0]))(["ABC","BC"]);}
export function canApp(){
return {
"Win.run":$can$s$57696e2e72756e,
};}
