// Generated by can compile from TemporalWire; do not edit.
import { hasRole } from "@canlang/stdlib";
import { list as $can$u$6c697374, message as $can$u$6d657373616765, text as $can$u$74657874 } from "@canlang/ui";
export const $can$p$54656d706f72616c576972653a64657363726970746f723a2f={owner:"TemporalWire",path:"/",title:$can$u$6d657373616765("Temporal wire"),admit:async(c,routeBindings={})=>{return {};},render:$can$p$54656d706f72616c576972653a72656e6465723a2f};
export async function $can$p$54656d706f72616c576972653a72656e6465723a2f(c,bindings){return (await Promise.all([$can$u$6c697374({context:c,model:"TemporalWire.Item",renderRow:($can$l$303a726f77,$can$l$313a726f7756696577)=>{$can$l$303a726f77={...$can$l$303a726f77.fields,id:$can$l$303a726f77.id,version:$can$l$303a726f77.version===undefined?undefined:BigInt($can$l$303a726f77.version)};return [$can$u$74657874({context:$can$l$313a726f7756696577,values:[$can$u$6d657373616765("{x,date}",{},{x:{type:"date",value:$can$l$303a726f77.day}}),$can$u$6d657373616765("{x,time}",{},{x:{type:"datetime",value:$can$l$303a726f77.instant}}),$can$u$6d657373616765("{x,number}",{},{x:{type:"decimal",value:$can$l$303a726f77.amount}})]})];}})])).filter(value=>value!=null).join('');}
export const appDefinition={id:"TemporalWire",uses:[],packages:{TemporalWire:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{"TemporalWire.Item":{readGrants:[{rule:"Item.read.1"}],fields:{day:{type:"date"},instant:{type:"datetime"},amount:{type:"decimal"}}}},preferences:{},operations:{},policy:{roles:[],models:{"TemporalWire.Item":{read:["Item.read.1"]}},operations:{}},pages:[$can$p$54656d706f72616c576972653a64657363726970746f723a2f],disabled:["TemporalWire.Item.create","TemporalWire.Item.update","TemporalWire.Item.delete"]};
export function canApp(){
return {
operations:[{"name":"TemporalWire.Item.read","kind":"read","description":"","inputs":{"fields":[]}}],
read:{"Item.read.1":(c,row)=>hasRole(c,"members")},
policy:{roles:[],models:{"TemporalWire.Item":{read:["Item.read.1"]}},operations:{}},
};}
