// Generated by can compile from AliasAudit; do not edit.
import { format } from "@canlang/stdlib";
import { message as $can$u$6d657373616765 } from "@canlang/ui";
export const appDefinition={id:"AliasAudit",uses:[],packages:{AliasAudit:{roles:{}},Owner:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{},pages:[],disabled:[]};
async function $can$s$416c69617341756469742e776f7264(c){return "caller";}
async function $can$s$416c69617341756469742e72756e(c){return await (($can$a$30)=>$can$s$4f776e65722e636f6d70757465(c,void 0,void 0,$can$a$30[0]))(["third"]);}
async function $can$s$416c69617341756469742e696e7370656374(c){return await (async($can$a$31)=>{const $can$l$323a63=await $can$s$4f776e65722e776f7264(c);const $can$l$333a636c617373=$can$l$323a63;const $can$l$343a6177616974=$can$a$31[0];return $can$u$6d657373616765("{c}/{class}/{await}",{},{c:{type:"text",value:$can$l$323a63},class:{type:"text",value:$can$l$333a636c617373},await:{type:"text",value:$can$l$343a6177616974}});})(["supplied"]);}
async function $can$s$4f776e65722e776f7264(c){return "owner";}
export async function $can$s$4f776e65722e636f6d70757465(c,$can$l$353a63,$can$l$363a7365636f6e64,$can$l$373a7468697264){if($can$l$353a63===undefined){$can$l$353a63=await $can$s$4f776e65722e776f7264(c);}if($can$l$363a7365636f6e64===undefined){$can$l$363a7365636f6e64=$can$l$353a63;}if($can$l$373a7468697264===undefined){$can$l$373a7468697264=$can$l$363a7365636f6e64;}return format("{c}/{second}/{third}",{c:$can$l$353a63,second:$can$l$363a7365636f6e64,third:$can$l$373a7468697264});}
export function canApp(){
return {
"AliasAudit.word":$can$s$416c69617341756469742e776f7264,
"AliasAudit.run":$can$s$416c69617341756469742e72756e,
"AliasAudit.inspect":$can$s$416c69617341756469742e696e7370656374,
"Owner.word":$can$s$4f776e65722e776f7264,
"Owner.compute":$can$s$4f776e65722e636f6d70757465,
};}
