import type * as Export0 from "@canlang/cloudflare";
export type Check0 = typeof Export0;
import type * as Export1 from "@canlang/cloudflare/worker";
export type Check1 = typeof Export1;
import type * as Export2 from "@canlang/cloudflare/runtime/artifact";
export type Check2 = typeof Export2;
import type * as Export3 from "@canlang/cloudflare/deploy/compat";
export type Check3 = typeof Export3;
import type * as Export4 from "@canlang/cloudflare/worker/assembly";
export type Check4 = typeof Export4;
import type * as Export5 from "@canlang/cloudflare/runtime/modules";
export type Check5 = typeof Export5;
import type * as Export6 from "@canlang/cloudflare/runtime/mcp-registry";
export type Check6 = typeof Export6;
import type * as Export7 from "@canlang/cloudflare/deploy/bundle";
export type Check7 = typeof Export7;
import type * as Export8 from "@canlang/cloudflare/dev/local-run";
export type Check8 = typeof Export8;
import type * as Export9 from "@canlang/cloudflare/runtime/stdlib";
export type Check9 = typeof Export9;
import type * as Export10 from "@canlang/cloudflare/dev/row-scope";
export type Check10 = typeof Export10;
import type * as Export11 from "@canlang/cloudflare/worker/main";
export type Check11 = typeof Export11;
import type * as Export12 from "@canlang/cloudflare/deploy/package-assets";
export type Check12 = typeof Export12;
import type * as Export13 from "@canlang/cloudflare/deploy/producer-files";
export type Check13 = typeof Export13;
import type * as Export14 from "@canlang/contracts";
export type Check14 = typeof Export14;
import type * as Export15 from "@canlang/contracts/distribution";
export type Check15 = typeof Export15;
import type * as Export16 from "@canlang/contracts/values";
export type Check16 = typeof Export16;
import type * as Export17 from "@canlang/files";
export type Check17 = typeof Export17;
import type * as Export18 from "@canlang/files/bridge";
export type Check18 = typeof Export18;
import type * as Export19 from "@canlang/files/catalog";
export type Check19 = typeof Export19;
import type * as Export20 from "@canlang/files/ports";
export type Check20 = typeof Export20;
import type * as Export21 from "@canlang/files/scenarios";
export type Check21 = typeof Export21;
import type * as Export22 from "@canlang/files/upload/fs-blob-store";
export type Check22 = typeof Export22;
import type * as Export23 from "@canlang/files/finalize";
export type Check23 = typeof Export23;
import type * as Export24 from "@canlang/files/provenance";
export type Check24 = typeof Export24;
import type * as Export25 from "@canlang/files/retention";
export type Check25 = typeof Export25;
import type * as Export26 from "@canlang/files/upload";
export type Check26 = typeof Export26;
import type * as Export27 from "@canlang/files/distribution";
export type Check27 = typeof Export27;
import type * as Export28 from "@canlang/identity";
export type Check28 = typeof Export28;
import type * as Export29 from "@canlang/identity/testing";
export type Check29 = typeof Export29;
import type * as Export30 from "@canlang/identity/distribution";
export type Check30 = typeof Export30;
import type * as Export31 from "@canlang/interfaces";
export type Check31 = typeof Export31;
import type * as Export32 from "@canlang/interfaces/distribution";
export type Check32 = typeof Export32;
import type * as Export33 from "@canlang/interfaces/testing";
export type Check33 = typeof Export33;
import type * as Export34 from "@canlang/interfaces/http/form-errors";
export type Check34 = typeof Export34;
import type * as Export35 from "@canlang/interfaces/uploads/kernel";
export type Check35 = typeof Export35;
import type * as Export36 from "@canlang/interfaces/mcp/server";
export type Check36 = typeof Export36;
import type * as Export37 from "@canlang/interfaces/http/operations";
export type Check37 = typeof Export37;
import type * as Export38 from "@canlang/services";
export type Check38 = typeof Export38;
import type * as Export39 from "@canlang/services/catalog";
export type Check39 = typeof Export39;
import type * as Export40 from "@canlang/services/http/client";
export type Check40 = typeof Export40;
import type * as Export41 from "@canlang/services/http/errors";
export type Check41 = typeof Export41;
import type * as Export42 from "@canlang/services/http/pagination";
export type Check42 = typeof Export42;
import type * as Export43 from "@canlang/services/judgments/harness";
export type Check43 = typeof Export43;
import type * as Export44 from "@canlang/services/judgments/systemone";
export type Check44 = typeof Export44;
import type * as Export45 from "@canlang/services/mail/adapter";
export type Check45 = typeof Export45;
import type * as Export46 from "@canlang/services/mail/redact";
export type Check46 = typeof Export46;
import type * as Export47 from "@canlang/services/media/comfyui";
export type Check47 = typeof Export47;
import type * as Export48 from "@canlang/services/media/harness";
export type Check48 = typeof Export48;
import type * as Export49 from "@canlang/services/media/mapping";
export type Check49 = typeof Export49;
import type * as Export50 from "@canlang/services/models/harness";
export type Check50 = typeof Export50;
import type * as Export51 from "@canlang/services/models/ollama";
export type Check51 = typeof Export51;
import type * as Export52 from "@canlang/services/ports";
export type Check52 = typeof Export52;
import type * as Export53 from "@canlang/services/scenarios";
export type Check53 = typeof Export53;
import type * as Export54 from "@canlang/services/distribution";
export type Check54 = typeof Export54;
import type * as Export55 from "@canlang/state";
export type Check55 = typeof Export55;
import type * as Export56 from "@canlang/state/catalog";
export type Check56 = typeof Export56;
import type * as Export57 from "@canlang/state/effects/staging";
export type Check57 = typeof Export57;
import type * as Export58 from "@canlang/state/errors";
export type Check58 = typeof Export58;
import type * as Export59 from "@canlang/state/fanout/cohort";
export type Check59 = typeof Export59;
import type * as Export60 from "@canlang/state/fanout/lifecycle";
export type Check60 = typeof Export60;
import type * as Export61 from "@canlang/state/fanout/membership";
export type Check61 = typeof Export61;
import type * as Export62 from "@canlang/state/fanout/outcome";
export type Check62 = typeof Export62;
import type * as Export63 from "@canlang/state/fanout/progress";
export type Check63 = typeof Export63;
import type * as Export64 from "@canlang/state/fanout/tables";
export type Check64 = typeof Export64;
import type * as Export65 from "@canlang/state/internal/json";
export type Check65 = typeof Export65;
import type * as Export66 from "@canlang/state/invocation/admission";
export type Check66 = typeof Export66;
import type * as Export67 from "@canlang/state/invocation/context";
export type Check67 = typeof Export67;
import type * as Export68 from "@canlang/state/invocation/invoke";
export type Check68 = typeof Export68;
import type * as Export69 from "@canlang/state/invocation/prepared-inputs";
export type Check69 = typeof Export69;
import type * as Export70 from "@canlang/state/invocation/registry";
export type Check70 = typeof Export70;
import type * as Export71 from "@canlang/state/invocation/replay";
export type Check71 = typeof Export71;
import type * as Export72 from "@canlang/state/migration/activate";
export type Check72 = typeof Export72;
import type * as Export73 from "@canlang/state/migration/mapper";
export type Check73 = typeof Export73;
import type * as Export74 from "@canlang/state/migration/recover";
export type Check74 = typeof Export74;
import type * as Export75 from "@canlang/state/migration/retain";
export type Check75 = typeof Export75;
import type * as Export76 from "@canlang/state/migration/stage";
export type Check76 = typeof Export76;
import type * as Export77 from "@canlang/state/migration/transition";
export type Check77 = typeof Export77;
import type * as Export78 from "@canlang/state/migration/validate";
export type Check78 = typeof Export78;
import type * as Export79 from "@canlang/state/mutation/crud";
export type Check79 = typeof Export79;
import type * as Export80 from "@canlang/state/mutation/models";
export type Check80 = typeof Export80;
import type * as Export81 from "@canlang/state/mutation/pipeline";
export type Check81 = typeof Export81;
import type * as Export82 from "@canlang/state/mutation/t18-shop.artifact";
export type Check82 = typeof Export82;
import type * as Export83 from "@canlang/state/policy/grants";
export type Check83 = typeof Export83;
import type * as Export84 from "@canlang/state/policy/roles";
export type Check84 = typeof Export84;
import type * as Export85 from "@canlang/state/ports/read";
export type Check85 = typeof Export85;
import type * as Export86 from "@canlang/state/ports/system";
export type Check86 = typeof Export86;
import type * as Export87 from "@canlang/state/ports/transact";
export type Check87 = typeof Export87;
import type * as Export88 from "@canlang/state/query/engine";
export type Check88 = typeof Export88;
import type * as Export89 from "@canlang/state/receipt/grants";
export type Check89 = typeof Export89;
import type * as Export90 from "@canlang/state/receipt/join";
export type Check90 = typeof Export90;
import type * as Export91 from "@canlang/state/receipt/tables";
export type Check91 = typeof Export91;
import type * as Export92 from "@canlang/state/storage/d1";
export type Check92 = typeof Export92;
import type * as Export93 from "@canlang/state/storage/durable-object";
export type Check93 = typeof Export93;
import type * as Export94 from "@canlang/state/storage/memory";
export type Check94 = typeof Export94;
import type * as Export95 from "@canlang/state/storage/port";
export type Check95 = typeof Export95;
import type * as Export96 from "@canlang/state/storage/schema";
export type Check96 = typeof Export96;
import type * as Export97 from "@canlang/state/invocation";
export type Check97 = typeof Export97;
import type * as Export98 from "@canlang/state/migration";
export type Check98 = typeof Export98;
import type * as Export99 from "@canlang/state/mutation";
export type Check99 = typeof Export99;
import type * as Export100 from "@canlang/state/ports";
export type Check100 = typeof Export100;
import type * as Export101 from "@canlang/state/query";
export type Check101 = typeof Export101;
import type * as Export102 from "@canlang/state/storage";
export type Check102 = typeof Export102;
import type * as Export103 from "@canlang/state/distribution";
export type Check103 = typeof Export103;
import type * as Export104 from "@canlang/state/receipt";
export type Check104 = typeof Export104;
import type * as Export105 from "@canlang/state/receipt/observer-loader";
export type Check105 = typeof Export105;
import type * as Export106 from "@canlang/state/testing/fanout/test-driver";
export type Check106 = typeof Export106;
import type * as Export107 from "@canlang/state/testing/invocation/fixtures";
export type Check107 = typeof Export107;
import type * as Export108 from "@canlang/state/testing/query/fixtures";
export type Check108 = typeof Export108;
import type * as Export109 from "@canlang/state/testing/mutation/fixtures";
export type Check109 = typeof Export109;
import type * as Export110 from "@canlang/stdlib";
export type Check110 = typeof Export110;
import type * as Export111 from "@canlang/stdlib/distribution";
export type Check111 = typeof Export111;
import type * as Export112 from "@canlang/testkit";
export type Check112 = typeof Export112;
import type * as Export113 from "@canlang/testkit/runner/dispatch";
export type Check113 = typeof Export113;
import type * as Export114 from "@canlang/testkit/runner/steps";
export type Check114 = typeof Export114;
import type * as Export115 from "@canlang/testkit/fixtures/b2-storage";
export type Check115 = typeof Export115;
import type * as Export116 from "@canlang/testkit/fixtures/playback";
export type Check116 = typeof Export116;
import type * as Export117 from "@canlang/testkit/fixtures/b2-delivery";
export type Check117 = typeof Export117;
import type * as Export118 from "@canlang/testkit/fixtures/b2-revocation";
export type Check118 = typeof Export118;
import type * as Export119 from "@canlang/ui";
export type Check119 = typeof Export119;
import type * as Export120 from "@canlang/ui/distribution";
export type Check120 = typeof Export120;
import type * as Export121 from "@canlang/ui/browser/export";
export type Check121 = typeof Export121;
import type * as Export122 from "@canlang/ui/browser/print";
export type Check122 = typeof Export122;
import type * as Export123 from "@canlang/values";
export type Check123 = typeof Export123;
import type * as Export124 from "@canlang/values/distribution";
export type Check124 = typeof Export124;
import type * as Export125 from "@canlang/values/bindings/backend";
export type Check125 = typeof Export125;
import type * as Export126 from "@canlang/values/bindings/bootstrap";
export type Check126 = typeof Export126;
import type * as Export127 from "@canlang/values/bindings/carriers";
export type Check127 = typeof Export127;
import type * as Export128 from "@canlang/values/bindings/owned-input";
export type Check128 = typeof Export128;
import type * as Export129 from "@canlang/values/bindings/plans";
export type Check129 = typeof Export129;
import type * as Export130 from "@canlang/values/bindings/validation";
export type Check130 = typeof Export130;
import type * as Export131 from "@canlang/values/bindings/generated/values_semantics.js";
export type Check131 = typeof Export131;
import type * as Export132 from "@canlang/work";
export type Check132 = typeof Export132;
import type * as Export133 from "@canlang/work/catalog";
export type Check133 = typeof Export133;
import type * as Export134 from "@canlang/work/kernel/commands";
export type Check134 = typeof Export134;
import type * as Export135 from "@canlang/work/kernel/tables";
export type Check135 = typeof Export135;
import type * as Export136 from "@canlang/work/observation/association";
export type Check136 = typeof Export136;
import type * as Export137 from "@canlang/work/observation/observation";
export type Check137 = typeof Export137;
import type * as Export138 from "@canlang/work/observation/ports";
export type Check138 = typeof Export138;
import type * as Export139 from "@canlang/work/ports";
export type Check139 = typeof Export139;
import type * as Export140 from "@canlang/work/schedule/every";
export type Check140 = typeof Export140;
import type * as Export141 from "@canlang/work/dispatch";
export type Check141 = typeof Export141;
import type * as Export142 from "@canlang/work/event";
export type Check142 = typeof Export142;
import type * as Export143 from "@canlang/work/intent";
export type Check143 = typeof Export143;
import type * as Export144 from "@canlang/work/receipt";
export type Check144 = typeof Export144;
import type * as Export145 from "@canlang/work/recovery";
export type Check145 = typeof Export145;
import type * as Export146 from "@canlang/work/schedule";
export type Check146 = typeof Export146;
import type * as Export147 from "@canlang/work/distribution";
export type Check147 = typeof Export147;
import type * as Export148 from "@canlang/work-kernel";
export type Check148 = typeof Export148;
import type * as Export149 from "@canlang/work-kernel/distribution";
export type Check149 = typeof Export149;
import { absInt } from "@canlang/stdlib";
import { createD1Storage } from "@canlang/state/storage/d1";
import type { StoragePort } from "@canlang/state/storage";
import type { D1Database } from "@cloudflare/workers-types";
const exactInteger: bigint = absInt(-1n);
declare const database: D1Database;
const storage: StoragePort = createD1Storage(database);
