// Generated by can compile from TemporalPage; do not edit.
import { message as $can$u$6d657373616765, text as $can$u$74657874 } from "@canlang/ui";
export const $can$p$54656d706f72616c506167653a64657363726970746f723a2f={owner:"TemporalPage",path:"/",title:$can$u$6d657373616765("Temporal"),admit:async(c,routeBindings={})=>{return {};},render:$can$p$54656d706f72616c506167653a72656e6465723a2f};
export async function $can$p$54656d706f72616c506167653a72656e6465723a2f(c,bindings){return (await Promise.all([$can$u$74657874({context:c,values:[$can$u$6d657373616765("{x,selectordinal,one {one} two {two} few {few} other {other}}",{},{x:{type:"int",value:2n}})]})])).filter(value=>value!=null).join('');}
export const appDefinition={id:"TemporalPage",uses:[],packages:{TemporalPage:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{},pages:[$can$p$54656d706f72616c506167653a64657363726970746f723a2f],disabled:[]};
export function canApp(){
return {
};}
