use canlang_compiler::{json::{self, Json}, lsp::transport::{read_message, MAX_MESSAGE_BYTES}, source::SourceId, syntax};
use std::io::{self, Read, BufRead};
use serde_json::{json,Value};
struct ObservedReader { data:Vec<u8>, at:usize, largest_read:usize, reads:usize }
impl Read for ObservedReader {fn read(&mut self,b:&mut[u8])->io::Result<usize>{self.largest_read=self.largest_read.max(b.len());self.reads+=1;let n=b.len().min(self.data.len()-self.at);b[..n].copy_from_slice(&self.data[self.at..self.at+n]);self.at+=n;Ok(n)}}
impl BufRead for ObservedReader {fn fill_buf(&mut self)->io::Result<&[u8]>{Ok(&self.data[self.at..])}fn consume(&mut self,n:usize){self.at+=n;}}
fn framing(label:&str,data:Vec<u8>)->Value{let total=data.len();let mut r=ObservedReader{data,at:0,largest_read:0,reads:0};let result=read_message(&mut r);json!({"case":label,"input_bytes":total,"consumed":r.at,"largest_read_buffer":r.largest_read,"read_calls":r.reads,"body_len":result.as_ref().ok().and_then(|x|x.as_ref().map(Vec::len)),"error":result.err().map(|x|format!("{:?}: {}",x.kind(),x))})}
fn main(){let a:Vec<String>=std::env::args().collect();let mode=a.get(1).map(String::as_str).unwrap_or("framing");
 match mode{
 "framing"=>{let large=2*1024*1024;let mut h=b"X-Audit: ".to_vec();h.extend(std::iter::repeat_n(b'x',large));h.extend(b"\r\nContent-Length: 0\r\n\r\n");let mut unterminated=b"X-Audit: ".to_vec();unterminated.extend(std::iter::repeat_n(b'x',large));let mut many=Vec::new();for _ in 0..8192{many.extend(b"X: y\r\n");}many.extend(b"Content-Length: 0\r\n\r\n");println!("{}",json!({"body_cap":MAX_MESSAGE_BYTES,"cases":[framing("empty",vec![]),framing("long-header",h),framing("unterminated-header",unterminated),framing("many-headers",many),framing("body-over-cap",format!("Content-Length: {}\r\n\r\n",MAX_MESSAGE_BYTES+1).into_bytes()),framing("body-at-cap-no-payload",format!("Content-Length: {MAX_MESSAGE_BYTES}\r\n\r\n").into_bytes()),framing("duplicate-length-last-wins",b"Content-Length: 8\r\nContent-Length: 2\r\n\r\n{}".to_vec())]}));},
 "parse-source"=>{let text=std::fs::read_to_string(&a[2]).unwrap();let(t,ds)=syntax::parse_source(SourceId(0),&text);let mut todo=vec![(&t,0)];let(mut count,mut height)=(0,0);while let Some((n,h))=todo.pop(){count+=1;height=height.max(h);for c in &n.children{todo.push((c,h+1));}}println!("{}",json!({"bytes":text.len(),"nodes":count,"height":height,"codes":ds.iter().map(|d|&d.code).collect::<Vec<_>>(),"coverage":t.verify_coverage(text.len()as u32).is_ok()}));},
 "json-width"=>{let n:usize=a[2].parse().unwrap();let text=format!("[{}]",std::iter::repeat_n("0",n).collect::<Vec<_>>().join(","));let v=json::parse(text.as_bytes()).unwrap();println!("{}",json!({"bytes":text.len(),"values":match v{Json::Arr(ref a)=>a.len(),_=>0}}));},
 "json-depth"=>{let n:usize=a[2].parse().unwrap();let text=format!("{}0{}","[".repeat(n),"]".repeat(n));let r=json::parse(text.as_bytes());println!("{}",json!({"depth":n,"bytes":text.len(),"accepted":r.is_ok(),"error":r.err().map(|e|e.to_string())}));},
 "json-invalid-num"=>{let r=std::panic::catch_unwind(||json::render(&Json::Num("not-a-number".into())));println!("{}",json!({"public_forged_carrier":true,"panic_caught":r.is_err()}));},
 "json-constructed-depth"=>{let n:usize=a[2].parse().unwrap();let mut v=Json::Null;for _ in 0..n{v=Json::Arr(vec![v]);}let r=json::render(&v);println!("{}",json!({"constructed_depth":n,"rendered_bytes":r.len(),"scope":"outside parser depth admission; public carrier serialization/drop"}));},
 _=>panic!("invalid audit mode")}}
