// Generated by can compile from T; do not edit.
import { count, format, starts_with } from "@canlang/stdlib";
import { message as $can$u$6d657373616765 } from "@canlang/ui";
export const appDefinition={id:"T",uses:[],packages:{T:{roles:{}}},bindings:{},contracts:{"T.Box":{fields:{left:{type:"text"},right:{type:"text"}}}},events:{},capabilities:{},models:{},preferences:{},operations:{},pages:[],disabled:[]};
async function $can$s$542e61(c,$can$l$303a76){return $can$l$303a76.left;}
async function $can$s$542e62(c,$can$l$313a76){return $can$l$313a76.right;}
async function $can$s$542e706f736974696f6e616c(c){return format("Hi {n}",{n:"Bo"});}
async function $can$s$542e6e616d6564(c){return format("Hi {n}",{n:"Bo"});}
async function $can$s$542e7265766572736564(c){return (($can$a$32)=>format($can$a$32[1],$can$a$32[0]))([{n:"Bo"},"Hi {n}"]);}
async function $can$s$542e6f726465726564(c,$can$l$333a76){return (($can$a$34)=>starts_with($can$a$34[1],$can$a$34[0]))([$can$l$333a76.left,$can$l$333a76.right]);}
async function $can$s$542e6d69786564(c,$can$l$353a76){return starts_with($can$l$353a76.right,$can$l$353a76.left);}
async function $can$s$542e666f726d61745f6f72646572(c,$can$l$363a76){return (($can$a$37)=>format($can$a$37[1],$can$a$37[0]))([{n:$can$l$363a76.right},$can$l$363a76.left]);}
async function $can$s$542e6e6573746564(c,$can$l$383a76){return (($can$a$39)=>starts_with($can$a$39[1],$can$a$39[0]))([await $can$s$542e61(c,$can$l$383a76),await $can$s$542e62(c,$can$l$383a76)]);}
async function $can$s$542e6c617a79(c,$can$l$31303a76){return false && (($can$a$3131)=>starts_with($can$a$3131[1],$can$a$3131[0]))([$can$l$31303a76.left,$can$l$31303a76.right]);}
async function $can$s$542e74616b65(c,$can$l$31323a61,$can$l$31333a62){return format("{a}|{b}",{a:$can$l$31323a61,b:$can$l$31333a62});}
async function $can$s$542e6e616d65645f646572697665(c,$can$l$31343a76){return await (($can$a$3135)=>$can$s$542e74616b65(c,$can$a$3135[1],$can$a$3135[0]))([$can$l$31343a76.right,$can$l$31343a76.left]);}
async function $can$s$542e66(c,$can$l$31363a61,$can$l$31373a62){if($can$l$31363a61===undefined){$can$l$31363a61="D";}if($can$l$31373a62===undefined){$can$l$31373a62=$can$l$31363a61;}return format("{a}|{b}",{a:$can$l$31363a61,b:$can$l$31373a62});}
async function $can$s$542e64656661756c7473(c){return await (($can$a$3138)=>$can$s$542e66(c,void 0,void 0))([]);}
async function $can$s$542e7061727469616c(c){return await (($can$a$3139)=>$can$s$542e66(c,$can$a$3139[0],void 0))(["A"]);}
async function $can$s$542e686f6c65(c){return await (($can$a$3230)=>$can$s$542e66(c,void 0,$can$a$3230[0]))(["B"]);}
async function $can$s$542e6578706c69636974(c){return await (($can$a$3231)=>$can$s$542e66(c,$can$a$3231[1],$can$a$3231[0]))(["B","A"]);}
async function $can$s$542e6e756c6c61626c65(c,$can$l$32323a61){if($can$l$32323a61===undefined){$can$l$32323a61="D";}return $can$l$32323a61;}
async function $can$s$542e6f6d69747465645f6e756c6c61626c65(c){return await (($can$a$3233)=>$can$s$542e6e756c6c61626c65(c,void 0))([]);}
async function $can$s$542e6578706c696369745f6e756c6c(c){return await $can$s$542e6e756c6c61626c65(c,null);}
async function $can$s$542e6765747465725f64656661756c7473(c,$can$l$32343a76,$can$l$32353a61,$can$l$32363a62){if($can$l$32353a61===undefined){$can$l$32353a61=$can$l$32343a76.left;}if($can$l$32363a62===undefined){$can$l$32363a62=$can$l$32343a76.right;}return format("{a}|{b}",{a:$can$l$32353a61,b:$can$l$32363a62});}
async function $can$s$542e6765747465725f73757070726573736564(c,$can$l$32373a76){return await (($can$a$3238)=>$can$s$542e6765747465725f64656661756c7473(c,$can$a$3238[0],$can$a$3238[1],void 0))([$can$l$32373a76,"manual"]);}
async function $can$s$542e64656661756c745f61667465725f737570706c696564(c,$can$l$32393a76){return await (($can$a$3330)=>$can$s$542e6765747465725f64656661756c7473(c,$can$a$3330[0],void 0,$can$a$3330[1]))([$can$l$32393a76,$can$l$32393a76.right]);}
async function $can$s$542e6173796e635f64656661756c74(c,$can$l$33313a76,$can$l$33323a61,$can$l$33333a62){if($can$l$33323a61===undefined){$can$l$33323a61=await $can$s$542e61(c,$can$l$33313a76);}if($can$l$33333a62===undefined){$can$l$33333a62=$can$l$33323a61;}return format("{a}|{b}",{a:$can$l$33323a61,b:$can$l$33333a62});}
async function $can$s$542e6173796e635f6f6d6974746564(c,$can$l$33343a76){return await (($can$a$3335)=>$can$s$542e6173796e635f64656661756c74(c,$can$a$3335[0],void 0,void 0))([$can$l$33343a76]);}
async function $can$s$542e7265736572766564(c,$can$l$33363a63,$can$l$33373a636c617373,$can$l$33383a6177616974){if($can$l$33363a63===undefined){$can$l$33363a63="C";}if($can$l$33373a636c617373===undefined){$can$l$33373a636c617373=$can$l$33363a63;}if($can$l$33383a6177616974===undefined){$can$l$33383a6177616974=$can$l$33373a636c617373;}return format("{a}|{b}|{d}",{a:$can$l$33363a63,b:$can$l$33373a636c617373,d:$can$l$33383a6177616974});}
async function $can$s$542e72657365727665645f63616c6c(c){return await (($can$a$3339)=>$can$s$542e7265736572766564(c,void 0,void 0,void 0))([]);}
async function $can$s$542e746578745f6964656e74697479(c,$can$l$34303a76){return $can$l$34303a76;}
async function $can$s$542e64657363726970746f725f64656661756c74(c){return (($can$a$3431)=>{const $can$l$34323a61="D";const $can$l$34333a62=$can$l$34323a61;return $can$u$6d657373616765("{a}|{b}",{},{a:{type:"text",value:$can$l$34323a61},b:{type:"text",value:$can$l$34333a62}});})([]);}
async function $can$s$542e64657363726970746f725f6e616d6564(c,$can$l$34343a76){return (($can$a$3435)=>{const $can$l$34363a61=$can$a$3435[1];const $can$l$34373a62=$can$a$3435[0];return $can$u$6d657373616765("{a}|{b}",{},{a:{type:"text",value:$can$l$34363a61},b:{type:"text",value:$can$l$34373a62}});})([$can$l$34343a76.right,$can$l$34343a76.left]);}
async function $can$s$542e64657363726970746f725f686f6c65(c,$can$l$34383a76){return (($can$a$3439)=>{const $can$l$35303a61="D";const $can$l$35313a62=$can$a$3439[0];return $can$u$6d657373616765("{a}|{b}",{},{a:{type:"text",value:$can$l$35303a61},b:{type:"text",value:$can$l$35313a62}});})([$can$l$34383a76.right]);}
async function $can$s$542e64657363726970746f725f6561726c696572(c,$can$l$35323a76){return (($can$a$3533)=>{const $can$l$35343a76=$can$a$3533[0];const $can$l$35353a61=$can$l$35343a76;const $can$l$35363a62=$can$l$35353a61;return $can$u$6d657373616765("{v}|{a}|{b}",{},{v:{type:"text",value:$can$l$35343a76},a:{type:"text",value:$can$l$35353a61},b:{type:"text",value:$can$l$35363a62}});})([$can$l$35323a76.left]);}
async function $can$s$542e64657363726970746f725f6173796e63(c,$can$l$35373a76){return await (async($can$a$3538)=>{const $can$l$35393a76=$can$a$3538[0];const $can$l$36303a61=await $can$s$542e746578745f6964656e74697479(c,$can$l$35393a76);const $can$l$36313a62=$can$l$36303a61;return $can$u$6d657373616765("{a}|{b}",{},{v:{type:"text",value:$can$l$35393a76},a:{type:"text",value:$can$l$36303a61},b:{type:"text",value:$can$l$36313a62}});})([$can$l$35373a76.left]);}
async function $can$s$542e6d6573736167655f64656661756c74(c){return count([(($can$a$3632)=>{const $can$l$36333a61="D";const $can$l$36343a62=$can$l$36333a61;return $can$u$6d657373616765("{a}|{b}",{},{a:{type:"text",value:$can$l$36333a61},b:{type:"text",value:$can$l$36343a62}});})([])]);}
async function $can$s$542e6d6573736167655f6e616d6564(c,$can$l$36353a76){return count([(($can$a$3636)=>{const $can$l$36373a61=$can$a$3636[1];const $can$l$36383a62=$can$a$3636[0];return $can$u$6d657373616765("{a}|{b}",{},{a:{type:"text",value:$can$l$36373a61},b:{type:"text",value:$can$l$36383a62}});})([$can$l$36353a76.right,$can$l$36353a76.left])]);}
async function $can$s$542e6d6573736167655f686f6c65(c,$can$l$36393a76){return count([(($can$a$3730)=>{const $can$l$37313a61="D";const $can$l$37323a62=$can$a$3730[0];return $can$u$6d657373616765("{a}|{b}",{},{a:{type:"text",value:$can$l$37313a61},b:{type:"text",value:$can$l$37323a62}});})([$can$l$36393a76.right])]);}
async function $can$s$542e6d6573736167655f6561726c696572(c,$can$l$37333a76){return count([(($can$a$3734)=>{const $can$l$37353a76=$can$a$3734[0];const $can$l$37363a61=$can$l$37353a76;const $can$l$37373a62=$can$l$37363a61;return $can$u$6d657373616765("{v}|{a}|{b}",{},{v:{type:"text",value:$can$l$37353a76},a:{type:"text",value:$can$l$37363a61},b:{type:"text",value:$can$l$37373a62}});})([$can$l$37333a76.left])]);}
async function $can$s$542e626164(c,$can$l$37383a74656d706c617465){return (($can$a$3739)=>format($can$a$3739[1],$can$a$3739[0]))([{other:"X"},$can$l$37383a74656d706c617465]);}
export function canApp(){
return {
"T.a":$can$s$542e61,
"T.b":$can$s$542e62,
"T.positional":$can$s$542e706f736974696f6e616c,
"T.named":$can$s$542e6e616d6564,
"T.reversed":$can$s$542e7265766572736564,
"T.ordered":$can$s$542e6f726465726564,
"T.mixed":$can$s$542e6d69786564,
"T.format_order":$can$s$542e666f726d61745f6f72646572,
"T.nested":$can$s$542e6e6573746564,
"T.lazy":$can$s$542e6c617a79,
"T.take":$can$s$542e74616b65,
"T.named_derive":$can$s$542e6e616d65645f646572697665,
"T.f":$can$s$542e66,
"T.defaults":$can$s$542e64656661756c7473,
"T.partial":$can$s$542e7061727469616c,
"T.hole":$can$s$542e686f6c65,
"T.explicit":$can$s$542e6578706c69636974,
"T.nullable":$can$s$542e6e756c6c61626c65,
"T.omitted_nullable":$can$s$542e6f6d69747465645f6e756c6c61626c65,
"T.explicit_null":$can$s$542e6578706c696369745f6e756c6c,
"T.getter_defaults":$can$s$542e6765747465725f64656661756c7473,
"T.getter_suppressed":$can$s$542e6765747465725f73757070726573736564,
"T.default_after_supplied":$can$s$542e64656661756c745f61667465725f737570706c696564,
"T.async_default":$can$s$542e6173796e635f64656661756c74,
"T.async_omitted":$can$s$542e6173796e635f6f6d6974746564,
"T.reserved":$can$s$542e7265736572766564,
"T.reserved_call":$can$s$542e72657365727665645f63616c6c,
"T.text_identity":$can$s$542e746578745f6964656e74697479,
"T.descriptor_default":$can$s$542e64657363726970746f725f64656661756c74,
"T.descriptor_named":$can$s$542e64657363726970746f725f6e616d6564,
"T.descriptor_hole":$can$s$542e64657363726970746f725f686f6c65,
"T.descriptor_earlier":$can$s$542e64657363726970746f725f6561726c696572,
"T.descriptor_async":$can$s$542e64657363726970746f725f6173796e63,
"T.message_default":$can$s$542e6d6573736167655f64656661756c74,
"T.message_named":$can$s$542e6d6573736167655f6e616d6564,
"T.message_hole":$can$s$542e6d6573736167655f686f6c65,
"T.message_earlier":$can$s$542e6d6573736167655f6561726c696572,
"T.bad":$can$s$542e626164,
};}
