// Generated by can compile from Shop; do not edit.
import { hasRole } from "@canlang/stdlib";
import { list as $can$u$6c697374, message as $can$u$6d657373616765 } from "@canlang/ui";
export const $can$p$53686f703a64657363726970746f723a2f={owner:"Shop",path:"/",title:$can$u$6d657373616765("Home"),admit:async(c,routeBindings={})=>{return {preferences:{Shop:{view:"all"}},};},render:$can$p$53686f703a72656e6465723a2f};
export async function $can$p$53686f703a72656e6465723a2f(c,bindings){return (await Promise.all([$can$u$6c697374({context:c,model:"Shop.Todo",order:[],renderRow:($can$l$303a726f77,$can$l$313a726f7756696577)=>{$can$l$303a726f77={...$can$l$303a726f77.fields,id:$can$l$303a726f77.id,version:$can$l$303a726f77.version===undefined?undefined:BigInt($can$l$303a726f77.version)};return [];}})])).filter(value=>value!=null).join('');}
export const appDefinition={id:"Shop",uses:[],packages:{Shop:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{"Shop.Todo":{readGrants:[{rule:"Todo.read.1"}],fields:{title:{type:"text"},priority:{type:"int"}}}},preferences:{Shop:{fields:{view:{type:"enum",cases:["all"],default:"all"}}}},operations:{},policy:{roles:[],models:{"Shop.Todo":{read:["Todo.read.1"]}},operations:{}},pages:[$can$p$53686f703a64657363726970746f723a2f],disabled:["Shop.Todo.create","Shop.Todo.update","Shop.Todo.delete"]};
export function canApp(){
return {
operations:[{"name":"Shop.Todo.read","kind":"read","description":"","inputs":{"fields":[]}}],
read:{"Todo.read.1":(c,row)=>hasRole(c,"members")},
policy:{roles:[],models:{"Shop.Todo":{read:["Todo.read.1"]}},operations:{}},
};}
