// Generated by can compile from Shop; do not edit.
import { message as $can$u$6d657373616765, tab as $can$u$746162, tabs as $can$u$74616273 } from "@canlang/ui";
export const $can$p$53686f703a64657363726970746f723a2f={owner:"Shop",path:"/",title:$can$u$6d657373616765("Home"),admit:async(c,routeBindings={})=>{return {};},render:$can$p$53686f703a72656e6465723a2f};
export async function $can$p$53686f703a72656e6465723a2f(c,bindings){return (await Promise.all([$can$u$74616273({context:c,children:[$can$u$746162({context:c})]})])).filter(value=>value!=null).join('');}
export const appDefinition={id:"Shop",uses:[],packages:{Shop:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{},pages:[$can$p$53686f703a64657363726970746f723a2f],disabled:[]};
export function canApp(){
return {
};}
