// Generated by can compile from NumericControl; do not edit.
import { require as check, create, deleteRecord, hasRole, int64, set } from "@canlang/stdlib";
export const $can$o$4e756d65726963436f6e74726f6c2e4a6f622e637265617465="NumericControl.Job.create";
export const $can$o$4e756d65726963436f6e74726f6c2e4a6f622e757064617465="NumericControl.Job.update";
export const $can$o$4e756d65726963436f6e74726f6c2e4a6f622e64656c657465="NumericControl.Job.delete";
export const $can$o$4e756d65726963436f6e74726f6c2e696e6372656d656e74="NumericControl.increment";
export const appDefinition={id:"NumericControl",uses:[],packages:{NumericControl:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{"NumericControl.Job":{readGrants:[{rule:"Job.read.1"}],fields:{count:{type:"int",default:1n}}}},preferences:{},operations:{"NumericControl.Job.create":{handler:"NumericControl.Job.create",kind:"create",model:"NumericControl.Job",read:false,inputs:{fields:["count"]},by:"public"},"NumericControl.Job.update":{handler:"NumericControl.Job.update",kind:"update",model:"NumericControl.Job",read:false,inputs:{record:{type:"NumericControl.Job"},changes:{fields:["count"]}},by:"public"},"NumericControl.Job.delete":{handler:"NumericControl.Job.delete",kind:"delete",model:"NumericControl.Job",read:false,inputs:{record:{type:"NumericControl.Job"}},by:"public"},"NumericControl.increment":{handler:"NumericControl.increment",inputs:{job:{type:"NumericControl.Job"}},by:"public",read:false,result:{type:"int"}}},policy:{roles:[],models:{"NumericControl.Job":{read:["Job.read.1"],public:["Job.read.1"]}},operations:{"NumericControl.Job.create":{by:["public"]},"NumericControl.Job.update":{by:["public"]},"NumericControl.Job.delete":{by:["public"]},"NumericControl.increment":{by:["public"]}}},pages:[],disabled:[]};
export function canApp(){
return {
operations:[{"name":"NumericControl.Job.read","kind":"read","description":"","inputs":{"fields":[]}},{"name":"NumericControl.Job.create","kind":"create","description":"","inputs":{"fields":[{"name":"count","field":{"kind":"integer"},"required":false,"default":{"kind":"literal","value":"1"}}]}},{"name":"NumericControl.Job.update","kind":"update","description":"","inputs":{"fields":[{"name":"record","field":{"kind":"ref","model":"NumericControl.Job","requireVersion":true},"required":true},{"name":"count","field":{"kind":"integer"},"required":false}]}},{"name":"NumericControl.Job.delete","kind":"delete","description":"","inputs":{"fields":[{"name":"record","field":{"kind":"ref","model":"NumericControl.Job","requireVersion":true},"required":true}]}},{"name":"NumericControl.increment","kind":"scenario","description":"","inputs":{"fields":[{"name":"job","field":{"kind":"ref","model":"NumericControl.Job","requireVersion":true},"required":true}]}}],
read:{"Job.read.1":(c,row)=>hasRole(c,"public")},
async "NumericControl.Job.create"(c,input){
check(hasRole(c,"public"),"forbidden");
await create(c,"NumericControl.Job",input);
},
async "NumericControl.Job.update"(c,{record,changes}){
check(hasRole(c,"public"),"forbidden");
await set(c,record,changes);
},
async "NumericControl.Job.delete"(c,{record}){
check(hasRole(c,"public"),"forbidden");
await deleteRecord(c,record,{mode:'archive'});
},
async "NumericControl.increment"(c,{job:$can$l$303a6a6f62}){
check(hasRole(c,"public"),"forbidden");
return int64($can$l$303a6a6f62.count + 1n);
},
policy:{roles:[],models:{"NumericControl.Job":{read:["Job.read.1"],public:["Job.read.1"]}},operations:{"NumericControl.Job.create":{by:["public"]},"NumericControl.Job.update":{by:["public"]},"NumericControl.Job.delete":{by:["public"]},"NumericControl.increment":{by:["public"]}}},
};}
