// Generated by can compile from T; do not edit.
export const appDefinition={id:"T",uses:[],packages:{T:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{"T.M":{readGrants:[],fields:{address:{type:"email",default:"用户@例子.公司"}}}},preferences:{},operations:{},pages:[],disabled:["T.M.create","T.M.update","T.M.delete"]};
export function canApp(){
return {
};}
