/**
 * T27 controlled provider output: generated bytes finalize through the
 * receiving-app intent lifecycle with frozen provider provenance.
 *
 * Unit battery over the memory harness (finalize/repeat/conflict/
 * invalid/oversized/expired/resume/permissions) plus FS-backed
 * end-to-end journeys through the controlled ComfyUI server and the
 * real adapter: provider bytes in, finalized receiving-app files out.
 */
import { describe, it, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type {
  ApiGraph,
  GeneratedImage,
  WorkflowNodeMapping,
} from '../../contracts/src/services.js';
import {
  ComfyUINativeAdapter,
  type HistoryImageDescriptor,
} from '../../services/src/media/comfyui.ts';
import { startControlledComfyServer } from '../../services/src/media/harness.ts';
import type { ControlledComfyServer } from '../../services/src/media/harness.ts';
import { digestGraph } from '../../services/src/media/mapping.ts';
import {
  appendUploadContent,
  completeUploadContent,
  createUploadIntent,
  sha256Hex,
  stagingKeyForIntent,
} from '../src/upload/index.ts';
import {
  authorizeAttach,
  blobKeyForFile,
  finalizeProviderOutput,
  providerRetryId,
  readFinalizedBytes,
  readFinalizedFile,
  recordAttachment,
  storedState,
  type ProviderOutputInput,
} from '../src/finalize/index.ts';
import { createFsBlobStore } from '../src/upload/fs-blob-store.ts';
import { describeForReceipt, runRetention } from '../src/retention/index.ts';
import type { RequestProvenanceBinding } from '../src/provenance/index.ts';
import {
  GARBAGE_BYTES,
  JPEG_BYTES,
  OTHER_PRINCIPAL,
  OTHER_TEAM,
  PDF_BYTES,
  PNG_BYTES,
  RECEIVER,
  T0,
  makeHarness,
  type FileHarness,
} from './helpers.ts';

const PROVIDER_BINDING: RequestProvenanceBinding = {
  adapter: 'deployment.comfyui',
  deliveryId: 'del_img_1',
  resultPath: 'outputs/0',
};

const OPERATION = 'std.ImagesV1.submit';
const FIELD = '/outputs/0';

function providerInput(overrides: Partial<ProviderOutputInput> = {}): ProviderOutputInput {
  return {
    receiver: RECEIVER,
    binding: PROVIDER_BINDING,
    operation: OPERATION,
    field: FIELD,
    args: {},
    name: 'ComfyUI_00001_.png',
    claimedType: 'image/png',
    bytes: PNG_BYTES,
    ...overrides,
  };
}

function joinOutput(h: FileHarness, input: ProviderOutputInput = providerInput()) {
  return finalizeProviderOutput(h.upload, h.finalize, input);
}

describe('t27 provider output finalization', () => {
  it('finalizes bytes with frozen controlled-provider provenance', () => {
    const h = makeHarness();
    const outcome = joinOutput(h);
    assert.equal(outcome.status, 'finalized');
    if (outcome.status !== 'finalized') {
      return;
    }
    assert.equal(outcome.result.file, outcome.file.id);
    assert.deepEqual(outcome.file.provenance, {
      kind: 'request',
      app: RECEIVER.app,
      team: RECEIVER.team,
      owner: RECEIVER.owner,
      principal: RECEIVER.principal,
      adapter: 'deployment.comfyui',
      deliveryId: 'del_img_1',
      resultPath: 'outputs/0',
    });
    assert.equal(Object.isFrozen(outcome.file), true);
    assert.equal(Object.isFrozen(outcome.file.provenance), true);
    assert.equal(outcome.file.contentType, 'image/png');
    assert.equal(outcome.file.sizeBytes, PNG_BYTES.length);
    assert.equal(outcome.file.bytesDigest, sha256Hex(PNG_BYTES));
    assert.deepEqual(outcome.file.finalizedAt, { kind: 'datetime', ms: BigInt(T0) });
    // No provider URL, filename or transport claim survives on the record.
    assert.deepEqual(Object.keys(outcome.file).sort(), [
      'bytesDigest',
      'contentType',
      'finalizedAt',
      'id',
      'provenance',
      'sizeBytes',
    ]);
    assert.deepEqual(readFinalizedBytes(h.finalize, outcome.file.id, RECEIVER), PNG_BYTES);
    assert.deepEqual(readFinalizedFile(h.finalize, outcome.file.id, RECEIVER), outcome.file);
  });

  it('lets detected bytes win over the transport claim', () => {
    const h = makeHarness();
    for (const claimedType of ['text/plain', 'image/jpeg', 'application/octet-stream']) {
      const slot = `outputs/claim-${claimedType.replace(/[^a-z]/g, '')}`;
      const outcome = joinOutput(
        h,
        providerInput({
          binding: { ...PROVIDER_BINDING, resultPath: slot },
          field: `/${slot}`,
          claimedType,
        }),
      );
      assert.equal(outcome.status, 'finalized');
      if (outcome.status !== 'finalized') {
        return;
      }
      assert.equal(outcome.file.contentType, 'image/png');
    }
  });

  it('finalizes JPEG bytes with their detected type', () => {
    const h = makeHarness();
    const outcome = joinOutput(
      h,
      providerInput({ bytes: JPEG_BYTES, name: 'photo.jpg', claimedType: 'image/jpeg' }),
    );
    assert.equal(outcome.status, 'finalized');
    if (outcome.status !== 'finalized') {
      return;
    }
    assert.equal(outcome.file.contentType, 'image/jpeg');
    assert.deepEqual(readFinalizedBytes(h.finalize, outcome.file.id, RECEIVER), JPEG_BYTES);
  });

  it('repeats identical bytes with the same reference', () => {
    const h = makeHarness();
    const first = joinOutput(h);
    assert.equal(first.status, 'finalized');
    if (first.status !== 'finalized') {
      return;
    }
    const second = joinOutput(h);
    assert.deepEqual(second, {
      status: 'repeated',
      result: { file: first.file.id },
      file: first.file,
    });
    assert.equal(h.files.listAll().length, 1);
    assert.equal(h.intents.listAll().length, 1);
  });

  it('conflicts on different bytes for the same slot', () => {
    const h = makeHarness();
    const first = joinOutput(h);
    assert.equal(first.status, 'finalized');
    if (first.status !== 'finalized') {
      return;
    }
    const other = new Uint8Array(PNG_BYTES);
    other[other.length - 1] = 0x02;
    assert.deepEqual(joinOutput(h, providerInput({ bytes: other })), {
      status: 'failed',
      reason: 'conflict',
    });
    assert.equal(h.files.listAll().length, 1);
    assert.deepEqual(readFinalizedBytes(h.finalize, first.file.id, RECEIVER), PNG_BYTES);
  });

  it('conflicts on different slot context', () => {
    const h = makeHarness();
    assert.equal(joinOutput(h).status, 'finalized');
    assert.deepEqual(joinOutput(h, providerInput({ operation: 'std.ImagesV1.inspect' })), {
      status: 'failed',
      reason: 'conflict',
    });
    assert.deepEqual(joinOutput(h, providerInput({ receiver: OTHER_PRINCIPAL })), {
      status: 'failed',
      reason: 'conflict',
    });
    assert.deepEqual(joinOutput(h, providerInput({ field: '/outputs/9' })), {
      status: 'failed',
      reason: 'conflict',
    });
    assert.equal(h.files.listAll().length, 1);
  });

  it('finalizes distinct slots as distinct files', () => {
    const h = makeHarness();
    const first = joinOutput(h);
    const second = joinOutput(
      h,
      providerInput({
        binding: { ...PROVIDER_BINDING, resultPath: 'outputs/1' },
        field: '/outputs/1',
        name: 'ComfyUI_00002_.png',
      }),
    );
    const third = joinOutput(
      h,
      providerInput({ binding: { ...PROVIDER_BINDING, deliveryId: 'del_img_2' } }),
    );
    assert.equal(first.status, 'finalized');
    assert.equal(second.status, 'finalized');
    assert.equal(third.status, 'finalized');
    if (
      first.status !== 'finalized' ||
      second.status !== 'finalized' ||
      third.status !== 'finalized'
    ) {
      return;
    }
    assert.notEqual(second.file.id, first.file.id);
    assert.notEqual(third.file.id, first.file.id);
    assert.equal(h.files.listAll().length, 3);
  });

  it('derives stable retry identities per slot', () => {
    assert.equal(
      providerRetryId(PROVIDER_BINDING),
      'provider:deployment.comfyui:del_img_1:outputs/0',
    );
    assert.equal(providerRetryId(PROVIDER_BINDING), providerRetryId({ ...PROVIDER_BINDING }));
    assert.notEqual(
      providerRetryId(PROVIDER_BINDING),
      providerRetryId({ ...PROVIDER_BINDING, resultPath: 'outputs/1' }),
    );
    assert.notEqual(
      providerRetryId(PROVIDER_BINDING),
      providerRetryId({ ...PROVIDER_BINDING, deliveryId: 'del_img_2' }),
    );
    assert.notEqual(
      providerRetryId(PROVIDER_BINDING),
      providerRetryId({ ...PROVIDER_BINDING, adapter: 'deployment.other' }),
    );
  });

  it('throws on non-byte input', () => {
    const h = makeHarness();
    assert.throws(
      () => joinOutput(h, providerInput({ bytes: [0x89] as unknown as Uint8Array })),
      /bytes must be a Uint8Array/,
    );
  });

  it('rejects malformed slot identities without storing anything', () => {
    const cases: Partial<ProviderOutputInput>[] = [
      { binding: { ...PROVIDER_BINDING, adapter: '' } },
      { operation: '' },
      { field: 'outputs/0' },
      { field: '/outputs/0', args: { outputs: { '0': 'taken' } } },
      { name: '' },
      { claimedType: '' },
    ];
    for (const overrides of cases) {
      const h = makeHarness();
      assert.deepEqual(joinOutput(h, providerInput(overrides)), {
        status: 'failed',
        reason: 'invalid-request',
      });
      assert.equal(h.files.listAll().length, 0);
      assert.equal(h.intents.listAll().length, 0);
    }
  });

  it('refuses undetectable provider bytes as malformed', () => {
    const h = makeHarness();
    assert.deepEqual(joinOutput(h, providerInput({ bytes: GARBAGE_BYTES })), {
      status: 'failed',
      reason: 'malformed',
    });
    assert.equal(h.files.listAll().length, 0);
    assert.equal(h.intents.listAll().length, 1);
    assert.equal(h.intents.listAll()[0]?.state, 'rejected');
  });

  it('refuses detected-but-excluded bytes under a narrow policy', () => {
    const h = makeHarness({ policy: { types: ['image/png', 'image/jpeg'], maxBytes: 1024 } });
    assert.deepEqual(joinOutput(h, providerInput({ bytes: PDF_BYTES })), {
      status: 'failed',
      reason: 'rejected',
    });
    assert.equal(h.files.listAll().length, 0);
  });

  it('refuses oversized provider bytes', () => {
    const h = makeHarness({ policy: { types: ['image/png'], maxBytes: 4 } });
    assert.deepEqual(joinOutput(h), {
      status: 'failed',
      reason: 'oversized',
    });
    assert.equal(h.files.listAll().length, 0);
    assert.equal(h.intents.listAll().length, 0);
  });

  it('expires slots whose intent TTL elapsed', () => {
    const h = makeHarness({ intentTtlMs: 0 });
    assert.deepEqual(joinOutput(h), {
      status: 'failed',
      reason: 'expired',
    });
    assert.equal(h.files.listAll().length, 0);
    const swept = h.intents.listAll()[0];
    assert.equal(swept?.state, 'expired');
    assert.equal(swept?.receivedBytes, 0);
  });

  it('expires complete slots after the clock advances', () => {
    const h = makeHarness();
    const retryId = providerRetryId(PROVIDER_BINDING);
    const created = createUploadIntent(h.upload, {
      request: {
        upload_id: retryId,
        operation: OPERATION,
        field: FIELD,
        arguments: {},
        name: 'ComfyUI_00001_.png',
        type: 'image/png',
        size: String(PNG_BYTES.length),
      },
      receiver: RECEIVER,
      binding: PROVIDER_BINDING,
    });
    assert.equal(created.status, 'granted');
    if (created.status !== 'granted') {
      return;
    }
    assert.equal(
      appendUploadContent(h.upload, created.intentId, RECEIVER, PNG_BYTES).status,
      'appended',
    );
    assert.equal(completeUploadContent(h.upload, created.intentId, RECEIVER).status, 'completed');
    h.clock.setNowMs(T0 + 16 * 60 * 1000);
    assert.deepEqual(joinOutput(h), {
      status: 'failed',
      reason: 'expired',
    });
    assert.equal(h.files.listAll().length, 0);
  });

  it('drives pre-created open slots to finalized', () => {
    const h = makeHarness();
    const created = createUploadIntent(h.upload, {
      request: {
        upload_id: providerRetryId(PROVIDER_BINDING),
        operation: OPERATION,
        field: FIELD,
        arguments: {},
        name: 'ComfyUI_00001_.png',
        type: 'image/png',
        size: String(PNG_BYTES.length),
      },
      receiver: RECEIVER,
      binding: PROVIDER_BINDING,
    });
    assert.equal(created.status, 'granted');
    const outcome = joinOutput(h);
    assert.equal(outcome.status, 'finalized');
    if (outcome.status !== 'finalized') {
      return;
    }
    assert.deepEqual(readFinalizedBytes(h.finalize, outcome.file.id, RECEIVER), PNG_BYTES);
  });

  it('resumes partial staging after verifying the prefix', () => {
    const h = makeHarness();
    const created = createUploadIntent(h.upload, {
      request: {
        upload_id: providerRetryId(PROVIDER_BINDING),
        operation: OPERATION,
        field: FIELD,
        arguments: {},
        name: 'ComfyUI_00001_.png',
        type: 'image/png',
        size: String(PNG_BYTES.length),
      },
      receiver: RECEIVER,
      binding: PROVIDER_BINDING,
    });
    assert.equal(created.status, 'granted');
    if (created.status !== 'granted') {
      return;
    }
    assert.equal(
      appendUploadContent(h.upload, created.intentId, RECEIVER, PNG_BYTES.slice(0, 4)).status,
      'appended',
    );
    const outcome = joinOutput(h);
    assert.equal(outcome.status, 'finalized');
    if (outcome.status !== 'finalized') {
      return;
    }
    assert.deepEqual(readFinalizedBytes(h.finalize, outcome.file.id, RECEIVER), PNG_BYTES);
  });

  it('conflicts when the staged prefix is not this transfer', () => {
    const h = makeHarness();
    const created = createUploadIntent(h.upload, {
      request: {
        upload_id: providerRetryId(PROVIDER_BINDING),
        operation: OPERATION,
        field: FIELD,
        arguments: {},
        name: 'ComfyUI_00001_.png',
        type: 'image/png',
        size: String(PNG_BYTES.length),
      },
      receiver: RECEIVER,
      binding: PROVIDER_BINDING,
    });
    assert.equal(created.status, 'granted');
    if (created.status !== 'granted') {
      return;
    }
    assert.equal(
      appendUploadContent(h.upload, created.intentId, RECEIVER, JPEG_BYTES.slice(0, 4)).status,
      'appended',
    );
    assert.deepEqual(joinOutput(h), {
      status: 'failed',
      reason: 'conflict',
    });
    assert.equal(h.files.listAll().length, 0);
  });

  it('conflicts on stale bytes under a fresh slot', () => {
    const h = makeHarness();
    const created = createUploadIntent(h.upload, {
      request: {
        upload_id: providerRetryId(PROVIDER_BINDING),
        operation: OPERATION,
        field: FIELD,
        arguments: {},
        name: 'ComfyUI_00001_.png',
        type: 'image/png',
        size: String(PNG_BYTES.length),
      },
      receiver: RECEIVER,
      binding: PROVIDER_BINDING,
    });
    assert.equal(created.status, 'granted');
    if (created.status !== 'granted') {
      return;
    }
    h.blobs.write(stagingKeyForIntent(created.intentId), JPEG_BYTES);
    assert.deepEqual(joinOutput(h), {
      status: 'failed',
      reason: 'conflict',
    });
    assert.equal(h.files.listAll().length, 0);
  });

  it('conflicts when staged bytes differ under a completed slot', () => {
    const h = makeHarness();
    const created = createUploadIntent(h.upload, {
      request: {
        upload_id: providerRetryId(PROVIDER_BINDING),
        operation: OPERATION,
        field: FIELD,
        arguments: {},
        name: 'ComfyUI_00001_.png',
        type: 'image/png',
        size: String(PNG_BYTES.length),
      },
      receiver: RECEIVER,
      binding: PROVIDER_BINDING,
    });
    assert.equal(created.status, 'granted');
    if (created.status !== 'granted') {
      return;
    }
    assert.equal(
      appendUploadContent(h.upload, created.intentId, RECEIVER, PNG_BYTES).status,
      'appended',
    );
    const other = new Uint8Array(PNG_BYTES);
    other[other.length - 1] = 0x02;
    assert.deepEqual(joinOutput(h, providerInput({ bytes: other })), {
      status: 'failed',
      reason: 'conflict',
    });
    assert.equal(h.files.listAll().length, 0);
  });

  it('re-derives rejected verdicts without touching the record', () => {
    const h = makeHarness();
    assert.deepEqual(joinOutput(h, providerInput({ bytes: GARBAGE_BYTES })), {
      status: 'failed',
      reason: 'malformed',
    });
    assert.deepEqual(joinOutput(h, providerInput({ bytes: GARBAGE_BYTES })), {
      status: 'failed',
      reason: 'malformed',
    });
    const otherGarbage = new Uint8Array([0x09, 0x09, 0x09, 0x00]);
    assert.deepEqual(joinOutput(h, providerInput({ bytes: otherGarbage })), {
      status: 'failed',
      reason: 'malformed',
    });
    const textBytes = new TextEncoder().encode('ok!\n');
    assert.deepEqual(joinOutput(h, providerInput({ bytes: textBytes })), {
      status: 'failed',
      reason: 'conflict',
    });
    assert.equal(h.files.listAll().length, 0);
    assert.equal(h.intents.listAll().length, 1);
    assert.equal(h.intents.listAll()[0]?.state, 'rejected');
  });

  it('authorizes the owner and denies everyone else', () => {
    const h = makeHarness();
    const outcome = joinOutput(h);
    assert.equal(outcome.status, 'finalized');
    if (outcome.status !== 'finalized') {
      return;
    }
    const ref = outcome.file.id;
    assert.deepEqual(authorizeAttach(h.finalize, ref, RECEIVER), {
      status: 'authorized',
      ref,
    });
    assert.deepEqual(authorizeAttach(h.finalize, ref, OTHER_PRINCIPAL), {
      status: 'failed',
      reason: 'foreign',
    });
    assert.deepEqual(authorizeAttach(h.finalize, ref, OTHER_TEAM), {
      status: 'failed',
      reason: 'foreign',
    });
    assert.deepEqual(authorizeAttach(h.finalize, 'file_999', RECEIVER), {
      status: 'failed',
      reason: 'foreign',
    });
    assert.equal(readFinalizedBytes(h.finalize, ref, OTHER_PRINCIPAL), null);
    assert.equal(readFinalizedFile(h.finalize, ref, OTHER_TEAM), null);
    assert.deepEqual(recordAttachment(h.finalize, ref, 'Run_1', RECEIVER), {
      status: 'attached',
      ref,
    });
    assert.equal(storedState(h.finalize, ref), 'attached');
    assert.deepEqual(recordAttachment(h.finalize, ref, 'Run_2', OTHER_TEAM), {
      status: 'failed',
      reason: 'foreign',
    });
  });

  it('repeats the same reference after retention collects the bytes', () => {
    const h = makeHarness();
    const outcome = joinOutput(h);
    assert.equal(outcome.status, 'finalized');
    if (outcome.status !== 'finalized') {
      return;
    }
    const ref = outcome.file.id;
    const report = runRetention(h.retention, { unattachedHorizonMs: 0, retentionMs: 86_400_000 });
    assert.deepEqual(report.orphaned, [ref]);
    assert.deepEqual(joinOutput(h), {
      status: 'repeated',
      result: { file: ref },
      file: outcome.file,
    });
    assert.equal(readFinalizedBytes(h.finalize, ref, RECEIVER), null);
    assert.deepEqual(describeForReceipt(h.retention, ref), {
      file: ref,
      status: 'redacted',
      contentType: 'image/png',
      sizeBytes: PNG_BYTES.length,
    });
    assert.deepEqual(authorizeAttach(h.finalize, ref, RECEIVER), {
      status: 'failed',
      reason: 'expired',
    });
  });

  it('treats provider filenames as untrusted metadata, never paths', () => {
    const h = makeHarness();
    const outcome = joinOutput(h, providerInput({ name: '../../etc/x.png' }));
    assert.equal(outcome.status, 'finalized');
    if (outcome.status !== 'finalized') {
      return;
    }
    assert.equal(blobKeyForFile(outcome.file.id), `f_${outcome.file.id}.bin`);
    assert.deepEqual(readFinalizedBytes(h.finalize, outcome.file.id, RECEIVER), PNG_BYTES);
  });
});

/* -- T27 end to end: controlled provider run to finalized files. -- */

const GRAPH: ApiGraph = {
  '3': {
    class_type: 'KSampler',
    inputs: { seed: 1, steps: 20, latent_image: ['5', 0], model: ['4', 0] },
  },
  '4': {
    class_type: 'CheckpointLoaderSimple',
    inputs: { ckpt_name: 'x.safetensors' },
  },
  '5': {
    class_type: 'EmptyLatentImage',
    inputs: { width: 512, height: 512, batch_size: 1 },
  },
  '6': { class_type: 'CLIPTextEncode', inputs: { text: '', clip: ['4', 1] } },
  '7': { class_type: 'CLIPTextEncode', inputs: { text: '', clip: ['4', 1] } },
  '9': {
    class_type: 'SaveImage',
    inputs: { filename_prefix: 'ComfyUI', images: ['8', 0] },
  },
};

function mappingFor(graph: ApiGraph): WorkflowNodeMapping {
  return {
    workflow: 'poster-v1',
    graphDigest: digestGraph(graph),
    inputs: {
      prompt: { node: '6', key: 'text' },
      negative: { node: '7', key: 'text' },
      width: { node: '5', key: 'width' },
      height: { node: '5', key: 'height' },
      seed: { node: '3', key: 'seed' },
    },
    outputs: ['9'],
  };
}

function makeAdapter(baseUrl: string): ComfyUINativeAdapter {
  return new ComfyUINativeAdapter({
    baseUrl,
    timeoutMs: 5000,
    maxBodyBytes: 1_000_000,
    graph: GRAPH,
    mapping: mappingFor(GRAPH),
    clientId: 'test-binding',
    maxDownloadBytes: 1_000_000,
    maxOutputs: 8,
  });
}

function historyEntry(images: HistoryImageDescriptor[]) {
  return {
    status: { status_str: 'success', completed: true },
    outputs: { '9': { images } },
  };
}

function imageDescriptor(filename: string): HistoryImageDescriptor {
  return { node: '9', filename, subfolder: '', type: 'output' };
}

async function withServer<T>(
  scenario: Parameters<typeof startControlledComfyServer>[0],
  run: (server: ControlledComfyServer) => Promise<T>,
): Promise<T> {
  const server = await startControlledComfyServer(scenario);
  try {
    return await run(server);
  } finally {
    await server.close();
  }
}

const e2eDir = mkdtempSync(join(tmpdir(), 'canlang-files-t27-'));
after(() => {
  rmSync(e2eDir, { recursive: true, force: true });
});

describe('t27 controlled provider run to finalized files', () => {
  it('finalizes downloaded outputs with provider provenance on disk', async () => {
    const dir = join(e2eDir, 'run');
    const h = makeHarness({ blobs: createFsBlobStore(dir) });
    await withServer(
      {
        kind: 'accept',
        history: {
          job_1: historyEntry([
            imageDescriptor('ComfyUI_00001_.png'),
            imageDescriptor('ComfyUI_00002_.png'),
          ]),
        },
        files: {
          'ComfyUI_00001_.png': PNG_BYTES,
          'ComfyUI_00002_.png': JPEG_BYTES,
        },
      },
      async (server) => {
        const observed = await makeAdapter(server.url).reconcile('job_1', {
          deliveryId: 'del_img_1',
        });
        assert.equal(observed.status, 'succeeded');
        if (observed.status !== 'succeeded' || observed.result === null) {
          return;
        }
        assert.equal(observed.result.state, 'succeeded');
        assert.equal(observed.result.outputs.length, 2);

        const refs: string[] = [];
        const served: GeneratedImage[] = observed.result.outputs;
        for (let index = 0; index < served.length; index += 1) {
          const output = served[index] as GeneratedImage;
          const outcome = finalizeProviderOutput(h.upload, h.finalize, {
            receiver: RECEIVER,
            binding: {
              adapter: 'deployment.comfyui',
              deliveryId: 'del_img_1',
              resultPath: `outputs/${index}`,
            },
            operation: 'std.ImagesV1.submit',
            field: `/outputs/${index}`,
            args: {},
            name: `ComfyUI_0000${index + 1}_.png`,
            claimedType: output.contentType,
            bytes: output.bytes,
          });
          assert.equal(outcome.status, 'finalized');
          if (outcome.status !== 'finalized') {
            return;
          }
          refs.push(outcome.file.id);
          assert.deepEqual(outcome.file.provenance, {
            kind: 'request',
            app: RECEIVER.app,
            team: RECEIVER.team,
            owner: RECEIVER.owner,
            principal: RECEIVER.principal,
            adapter: 'deployment.comfyui',
            deliveryId: 'del_img_1',
            resultPath: `outputs/${index}`,
          });
        }
        assert.equal(new Set(refs).size, 2);

        assert.deepEqual(readFinalizedBytes(h.finalize, refs[0] as string, RECEIVER), PNG_BYTES);
        assert.deepEqual(readFinalizedBytes(h.finalize, refs[1] as string, RECEIVER), JPEG_BYTES);
        assert.deepEqual(
          new Uint8Array(readFileSync(join(dir, blobKeyForFile(refs[0] as string)))),
          PNG_BYTES,
        );

        const attached = recordAttachment(h.finalize, refs[0] as string, 'Run_1', RECEIVER);
        assert.deepEqual(attached, { status: 'attached', ref: refs[0] });
        assert.deepEqual(
          server.requests.map((request) => request.path.split('?')[0]),
          ['/history/job_1', '/view', '/view'],
        );
      },
    );
  });

  it('finalizes nothing when provider bytes are invalid', async () => {
    const h = makeHarness({ blobs: createFsBlobStore(join(e2eDir, 'invalid')) });
    await withServer(
      {
        kind: 'accept',
        history: { job_2: historyEntry([imageDescriptor('bad.png')]) },
        files: { 'bad.png': GARBAGE_BYTES },
      },
      async (server) => {
        const observed = await makeAdapter(server.url).reconcile('job_2', {
          deliveryId: 'del_img_2',
        });
        assert.equal(observed.status, 'succeeded');
        if (observed.status !== 'succeeded' || observed.result === null) {
          return;
        }
        assert.equal(observed.result.outputs.length, 1);
        const output = observed.result.outputs[0] as GeneratedImage;
        assert.deepEqual(
          finalizeProviderOutput(h.upload, h.finalize, {
            receiver: RECEIVER,
            binding: {
              adapter: 'deployment.comfyui',
              deliveryId: 'del_img_2',
              resultPath: 'outputs/0',
            },
            operation: 'std.ImagesV1.submit',
            field: '/outputs/0',
            args: {},
            name: 'bad.png',
            claimedType: output.contentType,
            bytes: output.bytes,
          }),
          { status: 'failed', reason: 'malformed' },
        );
        assert.equal(h.files.listAll().length, 0);
      },
    );
  });
});
