// Generated by can compile from T; do not edit.
import { require as check, date, hasRole } from "@canlang/stdlib";
import { message as $can$u$6d657373616765 } from "@canlang/ui";
export const $can$o$542e73="T.s";
export const appDefinition={id:"T",uses:[],packages:{T:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{"T.s":{handler:"T.s",inputs:{},by:"members",read:true,result:{type:"date"}}},policy:{roles:[],models:{},operations:{"T.s":{by:["members"]}}},pages:[],disabled:[]};
export function canApp(){
return {
operations:[{"name":"T.s","kind":"read","description":"","inputs":{"fields":[]}}],
async "T.s"(c,{}){
check(hasRole(c,"members"),"forbidden");
const $can$l$303a76616c7565 = date("0099-01-01");
const $can$l$313a6d7367 = $can$u$6d657373616765("{x,date}",{},{x:{type:"date",value:$can$l$303a76616c7565}});
return $can$l$303a76616c7565;
},
policy:{roles:[],models:{},operations:{"T.s":{by:["members"]}}},
};}
