// Generated by can compile from T; do not edit.
import { starts_with } from "@canlang/stdlib";
export const appDefinition={id:"T",uses:[],packages:{T:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{},pages:[],disabled:[]};
async function $can$s$542e67(c){return starts_with("A","AB");}
export function canApp(){
return {
"T.g":$can$s$542e67,
};}
