//! B3-I5 codegen tests: `forms` descriptors + `policy` manifest alongside
//! grants, byte-identical emission for sources without forms/policies.
//!
//! TEST-ONLY: artifacts are produced under the explicit test-only
//! incomplete-analysis acknowledgment with no catalog, exactly like the
//! hermetic `codegen.rs` goldens. Assertions read emitted JS only; no
//! module is executed and nothing here claims runtime success.

use canlang_compiler::analysis::check_program;
use canlang_compiler::codegen::{EmitOptions, EmitSources, emit};
use canlang_compiler::diagnostic::DiagnosticResult;
use canlang_compiler::source::{SourceDb, SourceId};
use canlang_compiler::{LANGUAGE_VERSION, SCHEMA_VERSION};

const PLAIN: &str = r#"app Plain
package shop
 Given
  export Widget {
   title:text,
  }
 When
  ## no operations in this package
 Then
  page / title="Shop"
"#;

const GATED: &str = r#"app Gated
package shop
 Given
  role clerk
  export Widget {
   title:text,
  }
  policy Widget read=members
  invariant Widget: trim(title)!=""
 When
  crud Widget by=members fields=title
  scenario checkout(cart:Widget) by=clerk
   require cart.title!=""
   do set cart {title="sold"}
 Then
  page / title="Shop"
   card "Buy"
    form Widget.create
     input title
"#;

const PUBLIC: &str = r#"app Pub
package shop
 Given
  export Spot {
   name:text,
  }
  policy Spot read=public
  export Member {
   name:text,
   active:bool,
  }
  policy Member read=members
  policy Member read=public where=row.active
 When
  crud Spot by=members fields=name
 Then
  page / title="Shop"
"#;

/// Emit the entry module JS for one source under the test-only ack.
fn entry_js(source: &str) -> String {
    let mut db = SourceDb::new();
    let id: SourceId = db.add("test.can".to_string(), source.to_string());
    let (program, diags) = check_program(&db, &[id], None);
    let mut result = DiagnosticResult::new("test", LANGUAGE_VERSION, SCHEMA_VERSION);
    result.add_sources(&db);
    result.diagnostics = diags;
    result.complete = false;
    result.finish();
    let sources = EmitSources {
        db: &db,
        result: &result,
        catalog: None,
        options: EmitOptions::test_only(),
    };
    let (artifact, _) = emit(&program, &sources);
    artifact
        .modules
        .first()
        .map(|m| m.js.clone())
        .unwrap_or_default()
}

#[test]
fn plain_snippet_emits_no_forms_or_policy_members() {
    let js = entry_js(PLAIN);
    assert!(!js.is_empty(), "plain snippet emits");
    assert!(!js.contains("forms:"), "no forms member:\n{js}");
    assert!(!js.contains("policy:"), "no policy member:\n{js}");
    assert_eq!(js, EXPECTED_PLAIN_JS);
}

#[test]
fn gated_snippet_emits_forms_and_policy_members() {
    let js = entry_js(GATED);
    for marker in [
        // Form descriptor: page form bound to the crud operation.
        "forms:[{page:\"/\",operation:\"shop.Widget.create\",fields:[\"title\"]}]",
        // Policy manifest: role, rule registries, admission summaries.
        "policy:{roles:[\"shop.clerk\"]",
        "\"shop.Widget\":{read:[\"Widget.read.1\"],invariants:[\"Widget.require.1\"]}",
        "\"shop.checkout\":{by:[\"shop.clerk\"],requires:1}",
        "\"shop.Widget.create\":{by:[\"members\"]}",
    ] {
        assert!(js.contains(marker), "missing marker: {marker}\n{js}");
    }
}

/// (B7 phase-1) `canApp()` carries the same policy manifest as
/// `appDefinition` (erasure fix); models entries mark exactly the
/// unconditionally-public grants. Predicated `read=public where=` and
/// non-public spellings stay unmarked (fail-closed).
#[test]
fn b7_canapp_policy_with_public_provenance() {
    let js = entry_js(PUBLIC);
    let canapp = js
        .split("export function canApp(){")
        .nth(1)
        .unwrap_or_default();
    assert!(
        canapp.contains("policy:{roles:[],models:{\"shop.Spot\":{read:[\"Spot.read.1\"],public:[\"Spot.read.1\"]}"),
        "canApp carries policy with public provenance:\n{js}"
    );
    assert!(
        canapp.contains("\"shop.Member\":{read:[\"Member.read.1\",\"Member.read.2\"]}"),
        "predicated/non-public grants stay unmarked:\n{js}"
    );
    // The manifest is shared, not forked: appDefinition carries it too.
    assert!(
        js.contains("export const appDefinition=")
            && js.matches("public:[\"Spot.read.1\"]").count() == 2,
        "one builder, two carriers:\n{js}"
    );
}

/// (B7 phase-1) Ops-side entries are untouched: explicit `by=public`
/// keeps emitting `by:[\"public\"]` (no new marking needed).
#[test]
fn b7_ops_public_spelling_unchanged() {
    let src = PUBLIC.replace(
        "crud Spot by=members fields=name",
        "crud Spot by=public fields=name",
    );
    let js = entry_js(&src);
    assert!(
        js.contains("\"shop.Spot.create\":{by:[\"public\"]}"),
        "ops explicit-public shape unchanged:\n{js}"
    );
}

const EXPECTED_PLAIN_JS: &str = r#"// Generated by can compile from Plain; do not edit.
import { message as $can$u$6d657373616765 } from "@canlang/ui";
export const $can$p$73686f703a64657363726970746f723a2f={owner:"shop",path:"/",title:$can$u$6d657373616765("Shop"),admit:async(c,routeBindings={})=>{return {};},render:$can$p$73686f703a72656e6465723a2f};
export async function $can$p$73686f703a72656e6465723a2f(c,bindings){return (await Promise.all([])).filter(value=>value!=null).join('');}
export const appDefinition={id:"Plain",uses:[],packages:{Plain:{roles:{}},shop:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{"shop.Widget":{exported:true,readGrants:[],fields:{title:{type:"text"}}}},preferences:{},operations:{},pages:[$can$p$73686f703a64657363726970746f723a2f],disabled:["shop.Widget.create","shop.Widget.update","shop.Widget.delete"]};
export function canApp(){
return {
};}
"#;
