//! B3-I5 codegen tests: `forms` descriptors + `policy` manifest alongside
//! grants, byte-identical emission for sources without forms/policies.
//!
//! TEST-ONLY: artifacts are produced under the explicit test-only
//! incomplete-analysis acknowledgment with no catalog, exactly like the
//! hermetic `codegen.rs` goldens. Assertions read emitted JS only; no
//! module is executed and nothing here claims runtime success.

use canlang_compiler::analysis::check_program;
use canlang_compiler::codegen::{EmitOptions, EmitSources, emit};
use canlang_compiler::diagnostic::DiagnosticResult;
use canlang_compiler::source::{SourceDb, SourceId};
use canlang_compiler::{LANGUAGE_VERSION, SCHEMA_VERSION};

const PLAIN: &str = r#"app Plain
package shop
 Given
  export Widget {
   title:text,
  }
 When
  ## no operations in this package
 Then
  page / title="Shop"
"#;

const GATED: &str = r#"app Gated
package shop
 Given
  role clerk
  export Widget {
   title:text,
  }
  policy Widget read=members
  invariant Widget: trim(title)!=""
 When
  crud Widget by=members fields=title
  scenario checkout(cart:Widget) by=clerk
   require cart.title!=""
   do set cart {title="sold"}
 Then
  page / title="Shop"
   card "Buy"
    form Widget.create
     input title
"#;

/// Emit the entry module JS for one source under the test-only ack.
fn entry_js(source: &str) -> String {
    let mut db = SourceDb::new();
    let id: SourceId = db.add("test.can".to_string(), source.to_string());
    let (program, diags) = check_program(&db, &[id], None);
    let mut result = DiagnosticResult::new("test", LANGUAGE_VERSION, SCHEMA_VERSION);
    result.add_sources(&db);
    result.diagnostics = diags;
    result.complete = false;
    result.finish();
    let sources = EmitSources {
        db: &db,
        result: &result,
        catalog: None,
        options: EmitOptions::test_only(),
    };
    let (artifact, _) = emit(&program, &sources);
    artifact
        .modules
        .first()
        .map(|m| m.js.clone())
        .unwrap_or_default()
}

#[test]
fn plain_snippet_emits_no_forms_or_policy_members() {
    let js = entry_js(PLAIN);
    assert!(!js.is_empty(), "plain snippet emits");
    assert!(!js.contains("forms:"), "no forms member:\n{js}");
    assert!(!js.contains("policy:"), "no policy member:\n{js}");
    assert_eq!(js, EXPECTED_PLAIN_JS);
}

#[test]
fn gated_snippet_emits_forms_and_policy_members() {
    let js = entry_js(GATED);
    for marker in [
        // Form descriptor: page form bound to the crud operation.
        "forms:[{page:\"/\",operation:\"shop.Widget.create\",fields:[\"title\"]}]",
        // Policy manifest: role, rule registries, admission summaries.
        "policy:{roles:[\"shop.clerk\"]",
        "\"shop.Widget\":{read:[\"Widget.read.1\"],invariants:[\"Widget.require.1\"]}",
        "\"shop.checkout\":{by:[\"shop.clerk\"],requires:1}",
        "\"shop.Widget.create\":{by:[\"members\"]}",
    ] {
        assert!(js.contains(marker), "missing marker: {marker}\n{js}");
    }
}

const EXPECTED_PLAIN_JS: &str = r#"// Generated by can compile from Plain; do not edit.
import { message, renderPage } from "@canlang/ui";
export const shopPageDescriptor={owner:"shop",path:"/",title:message("Shop"),admit:async(c,routeBindings={})=>{return {};},render:shopPage};
export async function shopPage(c,bindings){return renderPage(c,shopPageDescriptor,()=>[]);}
export const appDefinition={id:"Plain",uses:[],packages:{Plain:{roles:{}},shop:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{"shop.Widget":{exported:true,readGrants:[],fields:{title:{type:"text"}}}},preferences:{},operations:{},pages:[shopPageDescriptor],disabled:["shop.Widget.create","shop.Widget.update","shop.Widget.delete"]};
export function canApp(){
return {
};}
"#;
