// Generated by can compile from Consumer; do not edit.
import { count, format } from "@canlang/stdlib";
import { message as $can$u$6d657373616765 } from "@canlang/ui";
export const appDefinition={id:"Consumer",uses:[],packages:{Consumer:{roles:{}},Provider:{roles:{}}},bindings:{},contracts:{},events:{},capabilities:{},models:{},preferences:{},operations:{},pages:[],disabled:[]};
async function $can$s$436f6e73756d65722e776f7264(c){return "CONSUMER";}
async function $can$s$436f6e73756d65722e67(c){return await (($can$a$30)=>$can$s$50726f76696465722e74616b65(c,$can$a$30[1],$can$a$30[0]))(["B","A"]);}
async function $can$s$436f6e73756d65722e6f776e65725f64656661756c74(c){return await (($can$a$31)=>$can$s$50726f76696465722e74616b65(c,void 0,$can$a$31[0]))(["B"]);}
async function $can$s$436f6e73756d65722e64657363726970746f72(c){return await (async($can$a$32)=>{const $can$l$333a61=await $can$s$50726f76696465722e776f7264(c);const $can$l$343a62=$can$a$32[0];return $can$u$6d657373616765("{a}|{b}",{},{a:{type:"text",value:$can$l$333a61},b:{type:"text",value:$can$l$343a62}});})(["B"]);}
async function $can$s$436f6e73756d65722e6d7367(c){return count([await (async($can$a$35)=>{const $can$l$363a61=await $can$s$50726f76696465722e776f7264(c);const $can$l$373a62=$can$a$35[0];return $can$u$6d657373616765("{a}|{b}",{},{a:{type:"text",value:$can$l$363a61},b:{type:"text",value:$can$l$373a62}});})(["B"])]);}
async function $can$s$50726f76696465722e776f7264(c){return "D";}
export async function $can$s$50726f76696465722e74616b65(c,$can$l$383a61,$can$l$393a62){if($can$l$383a61===undefined){$can$l$383a61=await $can$s$50726f76696465722e776f7264(c);}if($can$l$393a62===undefined){$can$l$393a62=$can$l$383a61;}return format("{a}|{b}",{a:$can$l$383a61,b:$can$l$393a62});}
export function canApp(){
return {
"Consumer.word":$can$s$436f6e73756d65722e776f7264,
"Consumer.g":$can$s$436f6e73756d65722e67,
"Consumer.owner_default":$can$s$436f6e73756d65722e6f776e65725f64656661756c74,
"Consumer.descriptor":$can$s$436f6e73756d65722e64657363726970746f72,
"Consumer.msg":$can$s$436f6e73756d65722e6d7367,
"Provider.word":$can$s$50726f76696465722e776f7264,
"Provider.take":$can$s$50726f76696465722e74616b65,
};}
