import pathlib,json,hashlib
root=pathlib.Path('/Users/vince/Projects/canlang'); out=root/'implementation/compiler-completion/release-prerequisites';pins=json.loads((out/'source-pins.json').read_text());m=json.loads((out/'archives.json').read_text());current={p:(root/p).is_file() and hashlib.sha256((root/p).read_bytes()).hexdigest()==v for p,v in pins.items()};linux=json.loads((out/'linux-artifact.json').read_text());native=json.loads((out/'native-artifact.json').read_text());cmd=json.loads((out/'commands.json').read_text())
assert all(r['checksum_matches'] for r in m['packages']); assert all(r['exit']==0 for r in cmd['results']);assert all(r['exit']==0 for r in linux['probes'].values());assert 'build_exit=0' in (out/'linux-release.stdout').read_text()
checks=[]
for r in m['packages']:
 for f in r['license_notice_files']:
  p=out/'notices'/f['path'];assert hashlib.sha256(p.read_bytes()).hexdigest()==f['sha256'];checks.append(str(p.relative_to(out)))
production={p:v for p,v in current.items() if p.startswith('compiler/src/') or p in ['compiler/Cargo.toml','compiler/Cargo.lock','compiler/can-completions.bash','compiler/can-completions.zsh','compiler/can-completions.fish','.github/workflows/release.yml']}
receipt={'schema':1,'scope':'DEP-03 existing two release targets and selected declared Rust floor 1.99; no lower MSRV claim or release authorization','archive_packages':len(m['packages']),'archive_checksums_matched':len(m['packages']),'notice_files_verified':len(checks),'supplemental_notice':'pinned upstream SIMD MIT license for base64-simd and vsimd','whole_lock_unresolved_notice_sources':[],'current_source_pins_matched':sum(current.values()),'source_pin_count':len(current),'current_source_mismatches':[p for p,v in current.items() if not v],'production_input_pins':len(production),'production_input_matches':sum(production.values()),'production_input_mismatches':[p for p,v in production.items() if not v],'native_release_exit':0,'linux_release_exit':0,'native_artifact':native,'linux_artifact':{k:v for k,v in linux.items() if k!='probes'},'linux_probe_exits':{k:v['exit'] for k,v in linux['probes'].items()},'linux_build_command':['cargo','build','--release','--locked','--offline','--target-dir','/tmp/canlang-dep03-release-20261008/target'],'linux_environment':{'CARGO_HOME':'/tmp/canlang-dep03-release-20261008/cargo-home','CARGO_BUILD_JOBS':'2','CARGO_INCREMENTAL':'0'},'linux_input_tar_sha256':hashlib.sha256(pathlib.Path('/private/tmp/canlang-dep03-release-20261008/input.tar.gz').read_bytes()).hexdigest(),'remaining':'Review prepared notices against distribution payload; current workflow uploads binary/checksum only and does not attach notices. No publishing or workflow edit in this evidence scope.'}
(out/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps({k:receipt[k] for k in ['archive_checksums_matched','notice_files_verified','source_pin_count','current_source_pins_matched','current_source_mismatches','production_input_pins','production_input_matches','production_input_mismatches','native_release_exit','linux_release_exit']}));print('Linux',linux['bytes'],linux['sha256']);print((out/'linux-build.stderr').read_text().splitlines()[-1])
